// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.13.0
// source: module/meta/v1alpha1/meta.proto

package v1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ObjectMeta defines how an object uniquely identifies itself in the state
// alongside other objects of the same type
type ObjectMeta struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// id defines the unique identifier of an object in the state
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ObjectMeta) Reset() {
	*x = ObjectMeta{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apis_meta_v1alpha1_meta_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ObjectMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectMeta) ProtoMessage() {}

func (x *ObjectMeta) ProtoReflect() protoreflect.Message {
	mi := &file_apis_meta_v1alpha1_meta_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectMeta.ProtoReflect.Descriptor instead.
func (*ObjectMeta) Descriptor() ([]byte, []int) {
	return file_apis_meta_v1alpha1_meta_proto_rawDescGZIP(), []int{0}
}

func (x *ObjectMeta) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// TransitionMeta defines an object which causes state transitions
type TransitionMeta struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TransitionMeta) Reset() {
	*x = TransitionMeta{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apis_meta_v1alpha1_meta_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransitionMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransitionMeta) ProtoMessage() {}

func (x *TransitionMeta) ProtoReflect() protoreflect.Message {
	mi := &file_apis_meta_v1alpha1_meta_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransitionMeta.ProtoReflect.Descriptor instead.
func (*TransitionMeta) Descriptor() ([]byte, []int) {
	return file_apis_meta_v1alpha1_meta_proto_rawDescGZIP(), []int{1}
}

var File_apis_meta_v1alpha1_meta_proto protoreflect.FileDescriptor

var file_apis_meta_v1alpha1_meta_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x61, 0x70, 0x69, 0x73, 0x2f, 0x6d, 0x65, 0x74, 0x61, 0x2f, 0x76, 0x31, 0x61, 0x6c,
	0x70, 0x68, 0x61, 0x31, 0x2f, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x12, 0x74, 0x6d, 0x6f, 0x73, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70,
	0x68, 0x61, 0x31, 0x22, 0x1c, 0x0a, 0x0a, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x4d, 0x65, 0x74,
	0x61, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x22, 0x10, 0x0a, 0x0e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x4d,
	0x65, 0x74, 0x61, 0x42, 0x2d, 0x5a, 0x2b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x66, 0x64, 0x79, 0x6d, 0x79, 0x6c, 0x6a, 0x61, 0x2f, 0x74, 0x6d, 0x6f, 0x73, 0x2f,
	0x61, 0x70, 0x69, 0x73, 0x2f, 0x6d, 0x65, 0x74, 0x61, 0x2f, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68,
	0x61, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_apis_meta_v1alpha1_meta_proto_rawDescOnce sync.Once
	file_apis_meta_v1alpha1_meta_proto_rawDescData = file_apis_meta_v1alpha1_meta_proto_rawDesc
)

func file_apis_meta_v1alpha1_meta_proto_rawDescGZIP() []byte {
	file_apis_meta_v1alpha1_meta_proto_rawDescOnce.Do(func() {
		file_apis_meta_v1alpha1_meta_proto_rawDescData = protoimpl.X.CompressGZIP(file_apis_meta_v1alpha1_meta_proto_rawDescData)
	})
	return file_apis_meta_v1alpha1_meta_proto_rawDescData
}

var file_apis_meta_v1alpha1_meta_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_apis_meta_v1alpha1_meta_proto_goTypes = []interface{}{
	(*ObjectMeta)(nil),     // 0: tmos.meta.v1alpha1.ObjectMeta
	(*TransitionMeta)(nil), // 1: tmos.meta.v1alpha1.TransitionMeta
}
var file_apis_meta_v1alpha1_meta_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_apis_meta_v1alpha1_meta_proto_init() }
func file_apis_meta_v1alpha1_meta_proto_init() {
	if File_apis_meta_v1alpha1_meta_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_apis_meta_v1alpha1_meta_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ObjectMeta); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apis_meta_v1alpha1_meta_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TransitionMeta); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_apis_meta_v1alpha1_meta_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_apis_meta_v1alpha1_meta_proto_goTypes,
		DependencyIndexes: file_apis_meta_v1alpha1_meta_proto_depIdxs,
		MessageInfos:      file_apis_meta_v1alpha1_meta_proto_msgTypes,
	}.Build()
	File_apis_meta_v1alpha1_meta_proto = out.File
	file_apis_meta_v1alpha1_meta_proto_rawDesc = nil
	file_apis_meta_v1alpha1_meta_proto_goTypes = nil
	file_apis_meta_v1alpha1_meta_proto_depIdxs = nil
}
