// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.13.0
// source: x/crisis/v1alpha1/crisis.proto

package v1alpha1

import (
	v1alpha1 "github.com/fdymylja/tmos/core/coin/v1alpha1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MsgRegisterInvariant is used by modules to register invariant handlers
type MsgRegisterInvariant struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// invariant_state_transition is the state transition that must be called
	// when verifying the invariant
	InvariantStateTransition string `protobuf:"bytes,1,opt,name=invariant_state_transition,json=invariantStateTransition,proto3" json:"invariant_state_transition,omitempty"`
	// unneeded fields but kept for backwards compatibility with the cosmos-sdk
	InvariantName       string `protobuf:"bytes,2,opt,name=invariant_name,json=invariantName,proto3" json:"invariant_name,omitempty"`
	InvariantModuleName string `protobuf:"bytes,3,opt,name=invariant_module_name,json=invariantModuleName,proto3" json:"invariant_module_name,omitempty"`
	InvariantRoute      string `protobuf:"bytes,4,opt,name=invariant_route,json=invariantRoute,proto3" json:"invariant_route,omitempty"`
}

func (x *MsgRegisterInvariant) Reset() {
	*x = MsgRegisterInvariant{}
	if protoimpl.UnsafeEnabled {
		mi := &file_x_crisis_v1alpha1_crisis_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgRegisterInvariant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgRegisterInvariant) ProtoMessage() {}

func (x *MsgRegisterInvariant) ProtoReflect() protoreflect.Message {
	mi := &file_x_crisis_v1alpha1_crisis_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgRegisterInvariant.ProtoReflect.Descriptor instead.
func (*MsgRegisterInvariant) Descriptor() ([]byte, []int) {
	return file_x_crisis_v1alpha1_crisis_proto_rawDescGZIP(), []int{0}
}

func (x *MsgRegisterInvariant) GetInvariantStateTransition() string {
	if x != nil {
		return x.InvariantStateTransition
	}
	return ""
}

func (x *MsgRegisterInvariant) GetInvariantName() string {
	if x != nil {
		return x.InvariantName
	}
	return ""
}

func (x *MsgRegisterInvariant) GetInvariantModuleName() string {
	if x != nil {
		return x.InvariantModuleName
	}
	return ""
}

func (x *MsgRegisterInvariant) GetInvariantRoute() string {
	if x != nil {
		return x.InvariantRoute
	}
	return ""
}

// MsgVerifyInvariantCosmosSDK matches the cosmos-sdk verify invariant
type MsgVerifyInvariantCosmosSDK struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sender              string `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	InvariantModuleName string `protobuf:"bytes,2,opt,name=invariant_module_name,json=invariantModuleName,proto3" json:"invariant_module_name,omitempty"`
	InvariantRoute      string `protobuf:"bytes,3,opt,name=invariant_route,json=invariantRoute,proto3" json:"invariant_route,omitempty"`
}

func (x *MsgVerifyInvariantCosmosSDK) Reset() {
	*x = MsgVerifyInvariantCosmosSDK{}
	if protoimpl.UnsafeEnabled {
		mi := &file_x_crisis_v1alpha1_crisis_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgVerifyInvariantCosmosSDK) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgVerifyInvariantCosmosSDK) ProtoMessage() {}

func (x *MsgVerifyInvariantCosmosSDK) ProtoReflect() protoreflect.Message {
	mi := &file_x_crisis_v1alpha1_crisis_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgVerifyInvariantCosmosSDK.ProtoReflect.Descriptor instead.
func (*MsgVerifyInvariantCosmosSDK) Descriptor() ([]byte, []int) {
	return file_x_crisis_v1alpha1_crisis_proto_rawDescGZIP(), []int{1}
}

func (x *MsgVerifyInvariantCosmosSDK) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *MsgVerifyInvariantCosmosSDK) GetInvariantModuleName() string {
	if x != nil {
		return x.InvariantModuleName
	}
	return ""
}

func (x *MsgVerifyInvariantCosmosSDK) GetInvariantRoute() string {
	if x != nil {
		return x.InvariantRoute
	}
	return ""
}

type MsgVerifyInvariant struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sender           string `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	InvariantHandler string `protobuf:"bytes,2,opt,name=invariant_handler,json=invariantHandler,proto3" json:"invariant_handler,omitempty"`
}

func (x *MsgVerifyInvariant) Reset() {
	*x = MsgVerifyInvariant{}
	if protoimpl.UnsafeEnabled {
		mi := &file_x_crisis_v1alpha1_crisis_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgVerifyInvariant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgVerifyInvariant) ProtoMessage() {}

func (x *MsgVerifyInvariant) ProtoReflect() protoreflect.Message {
	mi := &file_x_crisis_v1alpha1_crisis_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgVerifyInvariant.ProtoReflect.Descriptor instead.
func (*MsgVerifyInvariant) Descriptor() ([]byte, []int) {
	return file_x_crisis_v1alpha1_crisis_proto_rawDescGZIP(), []int{2}
}

func (x *MsgVerifyInvariant) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *MsgVerifyInvariant) GetInvariantHandler() string {
	if x != nil {
		return x.InvariantHandler
	}
	return ""
}

type InvariantHandler struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StateTransition string `protobuf:"bytes,1,opt,name=state_transition,json=stateTransition,proto3" json:"state_transition,omitempty"`
	Module          string `protobuf:"bytes,2,opt,name=module,proto3" json:"module,omitempty"`
	Route           string `protobuf:"bytes,3,opt,name=route,proto3" json:"route,omitempty"`
}

func (x *InvariantHandler) Reset() {
	*x = InvariantHandler{}
	if protoimpl.UnsafeEnabled {
		mi := &file_x_crisis_v1alpha1_crisis_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InvariantHandler) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvariantHandler) ProtoMessage() {}

func (x *InvariantHandler) ProtoReflect() protoreflect.Message {
	mi := &file_x_crisis_v1alpha1_crisis_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvariantHandler.ProtoReflect.Descriptor instead.
func (*InvariantHandler) Descriptor() ([]byte, []int) {
	return file_x_crisis_v1alpha1_crisis_proto_rawDescGZIP(), []int{3}
}

func (x *InvariantHandler) GetStateTransition() string {
	if x != nil {
		return x.StateTransition
	}
	return ""
}

func (x *InvariantHandler) GetModule() string {
	if x != nil {
		return x.Module
	}
	return ""
}

func (x *InvariantHandler) GetRoute() string {
	if x != nil {
		return x.Route
	}
	return ""
}

type Params struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ConstantFee *v1alpha1.Coin `protobuf:"bytes,1,opt,name=constant_fee,json=constantFee,proto3" json:"constant_fee,omitempty"`
}

func (x *Params) Reset() {
	*x = Params{}
	if protoimpl.UnsafeEnabled {
		mi := &file_x_crisis_v1alpha1_crisis_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Params) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Params) ProtoMessage() {}

func (x *Params) ProtoReflect() protoreflect.Message {
	mi := &file_x_crisis_v1alpha1_crisis_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Params.ProtoReflect.Descriptor instead.
func (*Params) Descriptor() ([]byte, []int) {
	return file_x_crisis_v1alpha1_crisis_proto_rawDescGZIP(), []int{4}
}

func (x *Params) GetConstantFee() *v1alpha1.Coin {
	if x != nil {
		return x.ConstantFee
	}
	return nil
}

var File_x_crisis_v1alpha1_crisis_proto protoreflect.FileDescriptor

var file_x_crisis_v1alpha1_crisis_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x78, 0x2f, 0x63, 0x72, 0x69, 0x73, 0x69, 0x73, 0x2f, 0x76, 0x31, 0x61, 0x6c, 0x70,
	0x68, 0x61, 0x31, 0x2f, 0x63, 0x72, 0x69, 0x73, 0x69, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x16, 0x74, 0x6d, 0x6f, 0x73, 0x2e, 0x78, 0x2e, 0x63, 0x72, 0x69, 0x73, 0x69, 0x73, 0x2e,
	0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x1a, 0x1d, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x63,
	0x6f, 0x69, 0x6e, 0x2f, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2f, 0x63, 0x6f, 0x69,
	0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xd8, 0x01, 0x0a, 0x14, 0x4d, 0x73, 0x67, 0x52,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x49, 0x6e, 0x76, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x74,
	0x12, 0x3c, 0x0a, 0x1a, 0x69, 0x6e, 0x76, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x74, 0x5f, 0x73, 0x74,
	0x61, 0x74, 0x65, 0x5f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x18, 0x69, 0x6e, 0x76, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x74, 0x53,
	0x74, 0x61, 0x74, 0x65, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x25,
	0x0a, 0x0e, 0x69, 0x6e, 0x76, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x69, 0x6e, 0x76, 0x61, 0x72, 0x69, 0x61, 0x6e,
	0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x32, 0x0a, 0x15, 0x69, 0x6e, 0x76, 0x61, 0x72, 0x69, 0x61,
	0x6e, 0x74, 0x5f, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x13, 0x69, 0x6e, 0x76, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x74, 0x4d,
	0x6f, 0x64, 0x75, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x27, 0x0a, 0x0f, 0x69, 0x6e, 0x76,
	0x61, 0x72, 0x69, 0x61, 0x6e, 0x74, 0x5f, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0e, 0x69, 0x6e, 0x76, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x74, 0x52, 0x6f, 0x75,
	0x74, 0x65, 0x22, 0x92, 0x01, 0x0a, 0x1b, 0x4d, 0x73, 0x67, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79,
	0x49, 0x6e, 0x76, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x74, 0x43, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x53,
	0x44, 0x4b, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x32, 0x0a, 0x15, 0x69, 0x6e,
	0x76, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x74, 0x5f, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x13, 0x69, 0x6e, 0x76, 0x61, 0x72,
	0x69, 0x61, 0x6e, 0x74, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x27,
	0x0a, 0x0f, 0x69, 0x6e, 0x76, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x74, 0x5f, 0x72, 0x6f, 0x75, 0x74,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x69, 0x6e, 0x76, 0x61, 0x72, 0x69, 0x61,
	0x6e, 0x74, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x22, 0x59, 0x0a, 0x12, 0x4d, 0x73, 0x67, 0x56, 0x65,
	0x72, 0x69, 0x66, 0x79, 0x49, 0x6e, 0x76, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x74, 0x12, 0x16, 0x0a,
	0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73,
	0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x2b, 0x0a, 0x11, 0x69, 0x6e, 0x76, 0x61, 0x72, 0x69, 0x61,
	0x6e, 0x74, 0x5f, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x10, 0x69, 0x6e, 0x76, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x74, 0x48, 0x61, 0x6e, 0x64, 0x6c,
	0x65, 0x72, 0x22, 0x6b, 0x0a, 0x10, 0x49, 0x6e, 0x76, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x74, 0x48,
	0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x12, 0x29, 0x0a, 0x10, 0x73, 0x74, 0x61, 0x74, 0x65, 0x5f,
	0x74, 0x72, 0x61, 0x6e, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x6f, 0x75,
	0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x22,
	0x4a, 0x0a, 0x06, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x40, 0x0a, 0x0c, 0x63, 0x6f, 0x6e,
	0x73, 0x74, 0x61, 0x6e, 0x74, 0x5f, 0x66, 0x65, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1d, 0x2e, 0x74, 0x6d, 0x6f, 0x73, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x63, 0x6f, 0x69, 0x6e,
	0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x43, 0x6f, 0x69, 0x6e, 0x52, 0x0b,
	0x63, 0x6f, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x74, 0x46, 0x65, 0x65, 0x42, 0x2c, 0x5a, 0x2a, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x66, 0x64, 0x79, 0x6d, 0x79, 0x6c,
	0x6a, 0x61, 0x2f, 0x74, 0x6d, 0x6f, 0x73, 0x2f, 0x78, 0x2f, 0x63, 0x72, 0x69, 0x73, 0x69, 0x73,
	0x2f, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_x_crisis_v1alpha1_crisis_proto_rawDescOnce sync.Once
	file_x_crisis_v1alpha1_crisis_proto_rawDescData = file_x_crisis_v1alpha1_crisis_proto_rawDesc
)

func file_x_crisis_v1alpha1_crisis_proto_rawDescGZIP() []byte {
	file_x_crisis_v1alpha1_crisis_proto_rawDescOnce.Do(func() {
		file_x_crisis_v1alpha1_crisis_proto_rawDescData = protoimpl.X.CompressGZIP(file_x_crisis_v1alpha1_crisis_proto_rawDescData)
	})
	return file_x_crisis_v1alpha1_crisis_proto_rawDescData
}

var file_x_crisis_v1alpha1_crisis_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_x_crisis_v1alpha1_crisis_proto_goTypes = []interface{}{
	(*MsgRegisterInvariant)(nil),        // 0: tmos.x.crisis.v1alpha1.MsgRegisterInvariant
	(*MsgVerifyInvariantCosmosSDK)(nil), // 1: tmos.x.crisis.v1alpha1.MsgVerifyInvariantCosmosSDK
	(*MsgVerifyInvariant)(nil),          // 2: tmos.x.crisis.v1alpha1.MsgVerifyInvariant
	(*InvariantHandler)(nil),            // 3: tmos.x.crisis.v1alpha1.InvariantHandler
	(*Params)(nil),                      // 4: tmos.x.crisis.v1alpha1.Params
	(*v1alpha1.Coin)(nil),               // 5: tmos.core.coin.v1alpha1.Coin
}
var file_x_crisis_v1alpha1_crisis_proto_depIdxs = []int32{
	5, // 0: tmos.x.crisis.v1alpha1.Params.constant_fee:type_name -> tmos.core.coin.v1alpha1.Coin
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_x_crisis_v1alpha1_crisis_proto_init() }
func file_x_crisis_v1alpha1_crisis_proto_init() {
	if File_x_crisis_v1alpha1_crisis_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_x_crisis_v1alpha1_crisis_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgRegisterInvariant); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_x_crisis_v1alpha1_crisis_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgVerifyInvariantCosmosSDK); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_x_crisis_v1alpha1_crisis_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgVerifyInvariant); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_x_crisis_v1alpha1_crisis_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InvariantHandler); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_x_crisis_v1alpha1_crisis_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Params); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_x_crisis_v1alpha1_crisis_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_x_crisis_v1alpha1_crisis_proto_goTypes,
		DependencyIndexes: file_x_crisis_v1alpha1_crisis_proto_depIdxs,
		MessageInfos:      file_x_crisis_v1alpha1_crisis_proto_msgTypes,
	}.Build()
	File_x_crisis_v1alpha1_crisis_proto = out.File
	file_x_crisis_v1alpha1_crisis_proto_rawDesc = nil
	file_x_crisis_v1alpha1_crisis_proto_goTypes = nil
	file_x_crisis_v1alpha1_crisis_proto_depIdxs = nil
}
