// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.13.0
// source: core/rbac/xt/rbac_extension.proto

package xt

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// StateTransitionAccessControl allows to define
// access control for a state transition in its protobuf message option.
type StateTransitionAccessControl struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// external marks if the state transition can be called externally or not.
	External bool `protobuf:"varint,1,opt,name=external,proto3" json:"external,omitempty"`
}

func (x *StateTransitionAccessControl) Reset() {
	*x = StateTransitionAccessControl{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_rbac_xt_rbac_extension_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StateTransitionAccessControl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateTransitionAccessControl) ProtoMessage() {}

func (x *StateTransitionAccessControl) ProtoReflect() protoreflect.Message {
	mi := &file_core_rbac_xt_rbac_extension_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateTransitionAccessControl.ProtoReflect.Descriptor instead.
func (*StateTransitionAccessControl) Descriptor() ([]byte, []int) {
	return file_core_rbac_xt_rbac_extension_proto_rawDescGZIP(), []int{0}
}

func (x *StateTransitionAccessControl) GetExternal() bool {
	if x != nil {
		return x.External
	}
	return false
}

var file_core_rbac_xt_rbac_extension_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*StateTransitionAccessControl)(nil),
		Field:         12000000,
		Name:          "tmos.core.rbac.xt.state_transition_acl",
		Tag:           "bytes,12000000,opt,name=state_transition_acl",
		Filename:      "core/rbac/xt/rbac_extension.proto",
	},
}

// Extension fields to descriptorpb.MessageOptions.
var (
	// optional tmos.core.rbac.xt.StateTransitionAccessControl state_transition_acl = 12000000;
	E_StateTransitionAcl = &file_core_rbac_xt_rbac_extension_proto_extTypes[0]
)

var File_core_rbac_xt_rbac_extension_proto protoreflect.FileDescriptor

var file_core_rbac_xt_rbac_extension_proto_rawDesc = []byte{
	0x0a, 0x21, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x72, 0x62, 0x61, 0x63, 0x2f, 0x78, 0x74, 0x2f, 0x72,
	0x62, 0x61, 0x63, 0x5f, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x11, 0x74, 0x6d, 0x6f, 0x73, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x72,
	0x62, 0x61, 0x63, 0x2e, 0x78, 0x74, 0x1a, 0x20, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3a, 0x0a, 0x1c, 0x53, 0x74, 0x61, 0x74,
	0x65, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x78, 0x74, 0x65,
	0x72, 0x6e, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x65, 0x78, 0x74, 0x65,
	0x72, 0x6e, 0x61, 0x6c, 0x3a, 0x85, 0x01, 0x0a, 0x14, 0x73, 0x74, 0x61, 0x74, 0x65, 0x5f, 0x74,
	0x72, 0x61, 0x6e, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x61, 0x63, 0x6c, 0x12, 0x1f, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x80,
	0xb6, 0xdc, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2f, 0x2e, 0x74, 0x6d, 0x6f, 0x73, 0x2e, 0x63,
	0x6f, 0x72, 0x65, 0x2e, 0x72, 0x62, 0x61, 0x63, 0x2e, 0x78, 0x74, 0x2e, 0x53, 0x74, 0x61, 0x74,
	0x65, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x52, 0x12, 0x73, 0x74, 0x61, 0x74, 0x65, 0x54,
	0x72, 0x61, 0x6e, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x63, 0x6c, 0x42, 0x27, 0x5a, 0x25,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x66, 0x64, 0x79, 0x6d, 0x79,
	0x6c, 0x6a, 0x61, 0x2f, 0x74, 0x6d, 0x6f, 0x73, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x72, 0x62,
	0x61, 0x63, 0x2f, 0x78, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_core_rbac_xt_rbac_extension_proto_rawDescOnce sync.Once
	file_core_rbac_xt_rbac_extension_proto_rawDescData = file_core_rbac_xt_rbac_extension_proto_rawDesc
)

func file_core_rbac_xt_rbac_extension_proto_rawDescGZIP() []byte {
	file_core_rbac_xt_rbac_extension_proto_rawDescOnce.Do(func() {
		file_core_rbac_xt_rbac_extension_proto_rawDescData = protoimpl.X.CompressGZIP(file_core_rbac_xt_rbac_extension_proto_rawDescData)
	})
	return file_core_rbac_xt_rbac_extension_proto_rawDescData
}

var file_core_rbac_xt_rbac_extension_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_core_rbac_xt_rbac_extension_proto_goTypes = []interface{}{
	(*StateTransitionAccessControl)(nil), // 0: tmos.core.rbac.xt.StateTransitionAccessControl
	(*descriptorpb.MessageOptions)(nil),  // 1: google.protobuf.MessageOptions
}
var file_core_rbac_xt_rbac_extension_proto_depIdxs = []int32{
	1, // 0: tmos.core.rbac.xt.state_transition_acl:extendee -> google.protobuf.MessageOptions
	0, // 1: tmos.core.rbac.xt.state_transition_acl:type_name -> tmos.core.rbac.xt.StateTransitionAccessControl
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	1, // [1:2] is the sub-list for extension type_name
	0, // [0:1] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_core_rbac_xt_rbac_extension_proto_init() }
func file_core_rbac_xt_rbac_extension_proto_init() {
	if File_core_rbac_xt_rbac_extension_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_core_rbac_xt_rbac_extension_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StateTransitionAccessControl); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_core_rbac_xt_rbac_extension_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_core_rbac_xt_rbac_extension_proto_goTypes,
		DependencyIndexes: file_core_rbac_xt_rbac_extension_proto_depIdxs,
		MessageInfos:      file_core_rbac_xt_rbac_extension_proto_msgTypes,
		ExtensionInfos:    file_core_rbac_xt_rbac_extension_proto_extTypes,
	}.Build()
	File_core_rbac_xt_rbac_extension_proto = out.File
	file_core_rbac_xt_rbac_extension_proto_rawDesc = nil
	file_core_rbac_xt_rbac_extension_proto_goTypes = nil
	file_core_rbac_xt_rbac_extension_proto_depIdxs = nil
}
