// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.13.0
// source: x/authn/crypto/secp256k1/secp256k1.proto

package secp256k1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PubKey defines a secp256k1 public key
// Key is the compressed form of the pubkey. The first byte depends is a 0x02 byte
// if the y-coordinate is the lexicographically largest of the two associated with
// the x-coordinate. Otherwise the first byte is a 0x03.
// This prefix is followed with the x-coordinate.
type PubKey struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *PubKey) Reset() {
	*x = PubKey{}
	if protoimpl.UnsafeEnabled {
		mi := &file_x_authn_crypto_secp256k1_secp256k1_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PubKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PubKey) ProtoMessage() {}

func (x *PubKey) ProtoReflect() protoreflect.Message {
	mi := &file_x_authn_crypto_secp256k1_secp256k1_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PubKey.ProtoReflect.Descriptor instead.
func (*PubKey) Descriptor() ([]byte, []int) {
	return file_x_authn_crypto_secp256k1_secp256k1_proto_rawDescGZIP(), []int{0}
}

func (x *PubKey) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

// PrivKey defines a secp256k1 private key.
type PrivKey struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *PrivKey) Reset() {
	*x = PrivKey{}
	if protoimpl.UnsafeEnabled {
		mi := &file_x_authn_crypto_secp256k1_secp256k1_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PrivKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrivKey) ProtoMessage() {}

func (x *PrivKey) ProtoReflect() protoreflect.Message {
	mi := &file_x_authn_crypto_secp256k1_secp256k1_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrivKey.ProtoReflect.Descriptor instead.
func (*PrivKey) Descriptor() ([]byte, []int) {
	return file_x_authn_crypto_secp256k1_secp256k1_proto_rawDescGZIP(), []int{1}
}

func (x *PrivKey) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

var File_x_authn_crypto_secp256k1_secp256k1_proto protoreflect.FileDescriptor

var file_x_authn_crypto_secp256k1_secp256k1_proto_rawDesc = []byte{
	0x0a, 0x28, 0x78, 0x2f, 0x61, 0x75, 0x74, 0x68, 0x6e, 0x2f, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f,
	0x2f, 0x73, 0x65, 0x63, 0x70, 0x32, 0x35, 0x36, 0x6b, 0x31, 0x2f, 0x73, 0x65, 0x63, 0x70, 0x32,
	0x35, 0x36, 0x6b, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1c, 0x74, 0x6d, 0x6f, 0x73,
	0x2e, 0x78, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x6e, 0x2e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x2e,
	0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x22, 0x1a, 0x0a, 0x06, 0x50, 0x75, 0x62, 0x4b,
	0x65, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x03, 0x6b, 0x65, 0x79, 0x22, 0x1b, 0x0a, 0x07, 0x50, 0x72, 0x69, 0x76, 0x4b, 0x65, 0x79, 0x12,
	0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x42, 0x33, 0x5a, 0x31, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x66, 0x64, 0x79, 0x6d, 0x79, 0x6c, 0x6a, 0x61, 0x2f, 0x74, 0x6d, 0x6f, 0x73, 0x2f, 0x78, 0x2f,
	0x61, 0x75, 0x74, 0x68, 0x6e, 0x2f, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x2f, 0x73, 0x65, 0x63,
	0x70, 0x32, 0x35, 0x36, 0x6b, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_x_authn_crypto_secp256k1_secp256k1_proto_rawDescOnce sync.Once
	file_x_authn_crypto_secp256k1_secp256k1_proto_rawDescData = file_x_authn_crypto_secp256k1_secp256k1_proto_rawDesc
)

func file_x_authn_crypto_secp256k1_secp256k1_proto_rawDescGZIP() []byte {
	file_x_authn_crypto_secp256k1_secp256k1_proto_rawDescOnce.Do(func() {
		file_x_authn_crypto_secp256k1_secp256k1_proto_rawDescData = protoimpl.X.CompressGZIP(file_x_authn_crypto_secp256k1_secp256k1_proto_rawDescData)
	})
	return file_x_authn_crypto_secp256k1_secp256k1_proto_rawDescData
}

var file_x_authn_crypto_secp256k1_secp256k1_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_x_authn_crypto_secp256k1_secp256k1_proto_goTypes = []interface{}{
	(*PubKey)(nil),  // 0: tmos.x.authn.crypto.v1alpha1.PubKey
	(*PrivKey)(nil), // 1: tmos.x.authn.crypto.v1alpha1.PrivKey
}
var file_x_authn_crypto_secp256k1_secp256k1_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_x_authn_crypto_secp256k1_secp256k1_proto_init() }
func file_x_authn_crypto_secp256k1_secp256k1_proto_init() {
	if File_x_authn_crypto_secp256k1_secp256k1_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_x_authn_crypto_secp256k1_secp256k1_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PubKey); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_x_authn_crypto_secp256k1_secp256k1_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PrivKey); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_x_authn_crypto_secp256k1_secp256k1_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_x_authn_crypto_secp256k1_secp256k1_proto_goTypes,
		DependencyIndexes: file_x_authn_crypto_secp256k1_secp256k1_proto_depIdxs,
		MessageInfos:      file_x_authn_crypto_secp256k1_secp256k1_proto_msgTypes,
	}.Build()
	File_x_authn_crypto_secp256k1_secp256k1_proto = out.File
	file_x_authn_crypto_secp256k1_secp256k1_proto_rawDesc = nil
	file_x_authn_crypto_secp256k1_secp256k1_proto_goTypes = nil
	file_x_authn_crypto_secp256k1_secp256k1_proto_depIdxs = nil
}
