// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.13.0
// source: module/runtime/v1alpha1/runtime.proto

package v1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Verb defines an action that can be performed on the runtime by external entities
type Verb int32

const (
	// Unknown defines an unknown verb
	Verb_Unknown Verb = 0
	// Get identifies the GET operation
	Verb_Get Verb = 1
	// List identifies the LIST operation
	Verb_List Verb = 2
	// Create identifies the CREATE operation
	Verb_Create Verb = 3
	// Update identifies the UPDATE operation
	Verb_Update Verb = 4
	// Delete identifies the DELETE operation
	Verb_Delete Verb = 5
	// Deliver identifies the DELIVER operation
	Verb_Deliver Verb = 6
)

// Enum value maps for Verb.
var (
	Verb_name = map[int32]string{
		0: "Unknown",
		1: "Get",
		2: "List",
		3: "Create",
		4: "Update",
		5: "Delete",
		6: "Deliver",
	}
	Verb_value = map[string]int32{
		"Unknown": 0,
		"Get":     1,
		"List":    2,
		"Create":  3,
		"Update":  4,
		"Delete":  5,
		"Deliver": 6,
	}
)

func (x Verb) Enum() *Verb {
	p := new(Verb)
	*p = x
	return p
}

func (x Verb) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Verb) Descriptor() protoreflect.EnumDescriptor {
	return file_module_runtime_v1alpha1_runtime_proto_enumTypes[0].Descriptor()
}

func (Verb) Type() protoreflect.EnumType {
	return &file_module_runtime_v1alpha1_runtime_proto_enumTypes[0]
}

func (x Verb) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Verb.Descriptor instead.
func (Verb) EnumDescriptor() ([]byte, []int) {
	return file_module_runtime_v1alpha1_runtime_proto_rawDescGZIP(), []int{0}
}

var File_module_runtime_v1alpha1_runtime_proto protoreflect.FileDescriptor

var file_module_runtime_v1alpha1_runtime_proto_rawDesc = []byte{
	0x0a, 0x25, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x2f, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65,
	0x2f, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2f, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x15, 0x74, 0x6d, 0x6f, 0x73, 0x2e, 0x72, 0x75,
	0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2a, 0x57,
	0x0a, 0x04, 0x56, 0x65, 0x72, 0x62, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77,
	0x6e, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x47, 0x65, 0x74, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04,
	0x4c, 0x69, 0x73, 0x74, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x10, 0x03, 0x12, 0x0a, 0x0a, 0x06, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x10, 0x04, 0x12, 0x0a,
	0x0a, 0x06, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x10, 0x05, 0x12, 0x0b, 0x0a, 0x07, 0x44, 0x65,
	0x6c, 0x69, 0x76, 0x65, 0x72, 0x10, 0x06, 0x42, 0x32, 0x5a, 0x30, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x66, 0x64, 0x79, 0x6d, 0x79, 0x6c, 0x6a, 0x61, 0x2f, 0x74,
	0x6d, 0x6f, 0x73, 0x2f, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x2f, 0x72, 0x75, 0x6e, 0x74, 0x69,
	0x6d, 0x65, 0x2f, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_module_runtime_v1alpha1_runtime_proto_rawDescOnce sync.Once
	file_module_runtime_v1alpha1_runtime_proto_rawDescData = file_module_runtime_v1alpha1_runtime_proto_rawDesc
)

func file_module_runtime_v1alpha1_runtime_proto_rawDescGZIP() []byte {
	file_module_runtime_v1alpha1_runtime_proto_rawDescOnce.Do(func() {
		file_module_runtime_v1alpha1_runtime_proto_rawDescData = protoimpl.X.CompressGZIP(file_module_runtime_v1alpha1_runtime_proto_rawDescData)
	})
	return file_module_runtime_v1alpha1_runtime_proto_rawDescData
}

var file_module_runtime_v1alpha1_runtime_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_module_runtime_v1alpha1_runtime_proto_goTypes = []interface{}{
	(Verb)(0), // 0: tmos.runtime.v1alpha1.Verb
}
var file_module_runtime_v1alpha1_runtime_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_module_runtime_v1alpha1_runtime_proto_init() }
func file_module_runtime_v1alpha1_runtime_proto_init() {
	if File_module_runtime_v1alpha1_runtime_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_module_runtime_v1alpha1_runtime_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_module_runtime_v1alpha1_runtime_proto_goTypes,
		DependencyIndexes: file_module_runtime_v1alpha1_runtime_proto_depIdxs,
		EnumInfos:         file_module_runtime_v1alpha1_runtime_proto_enumTypes,
	}.Build()
	File_module_runtime_v1alpha1_runtime_proto = out.File
	file_module_runtime_v1alpha1_runtime_proto_rawDesc = nil
	file_module_runtime_v1alpha1_runtime_proto_goTypes = nil
	file_module_runtime_v1alpha1_runtime_proto_depIdxs = nil
}
