// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.13.0
// source: module/rbac/v1alpha1/rbac.proto

package v1alpha1

import (
	reflect "reflect"
	sync "sync"

	_ "github.com/fdymylja/tmos/module/meta/v1alpha1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Role defines a role, which defines what resources
// can be accessed and which operations can be performed
// on those resources
type Role struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Resources []string `protobuf:"bytes,2,rep,name=resources,proto3" json:"resources,omitempty"`
	Verbs     []string `protobuf:"bytes,3,rep,name=verbs,proto3" json:"verbs,omitempty"`
}

func (x *Role) Reset() {
	*x = Role{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apis_rbac_v1alpha1_rbac_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Role) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Role) ProtoMessage() {}

func (x *Role) ProtoReflect() protoreflect.Message {
	mi := &file_apis_rbac_v1alpha1_rbac_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Role.ProtoReflect.Descriptor instead.
func (*Role) Descriptor() ([]byte, []int) {
	return file_apis_rbac_v1alpha1_rbac_proto_rawDescGZIP(), []int{0}
}

func (x *Role) GetResources() []string {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *Role) GetVerbs() []string {
	if x != nil {
		return x.Verbs
	}
	return nil
}

// RoleBinding binds a subject to a role
type RoleBinding struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Subject string `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`                // uniquely identifies the account
	RoleRef string `protobuf:"bytes,2,opt,name=role_ref,json=roleRef,proto3" json:"role_ref,omitempty"` // points to Role
}

func (x *RoleBinding) Reset() {
	*x = RoleBinding{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apis_rbac_v1alpha1_rbac_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoleBinding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleBinding) ProtoMessage() {}

func (x *RoleBinding) ProtoReflect() protoreflect.Message {
	mi := &file_apis_rbac_v1alpha1_rbac_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleBinding.ProtoReflect.Descriptor instead.
func (*RoleBinding) Descriptor() ([]byte, []int) {
	return file_apis_rbac_v1alpha1_rbac_proto_rawDescGZIP(), []int{1}
}

func (x *RoleBinding) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *RoleBinding) GetRoleRef() string {
	if x != nil {
		return x.RoleRef
	}
	return ""
}

var File_apis_rbac_v1alpha1_rbac_proto protoreflect.FileDescriptor

var file_apis_rbac_v1alpha1_rbac_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x61, 0x70, 0x69, 0x73, 0x2f, 0x72, 0x62, 0x61, 0x63, 0x2f, 0x76, 0x31, 0x61, 0x6c,
	0x70, 0x68, 0x61, 0x31, 0x2f, 0x72, 0x62, 0x61, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x12, 0x74, 0x6d, 0x6f, 0x73, 0x2e, 0x72, 0x62, 0x61, 0x63, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70,
	0x68, 0x61, 0x31, 0x1a, 0x1d, 0x61, 0x70, 0x69, 0x73, 0x2f, 0x6d, 0x65, 0x74, 0x61, 0x2f, 0x76,
	0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2f, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x3a, 0x0a, 0x04, 0x52, 0x6f, 0x6c, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x72,
	0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x65, 0x72, 0x62,
	0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x76, 0x65, 0x72, 0x62, 0x73, 0x22, 0x42,
	0x0a, 0x0b, 0x52, 0x6f, 0x6c, 0x65, 0x42, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x12, 0x18, 0x0a,
	0x07, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x72, 0x6f, 0x6c, 0x65, 0x5f,
	0x72, 0x65, 0x66, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x72, 0x6f, 0x6c, 0x65, 0x52,
	0x65, 0x66, 0x42, 0x2d, 0x5a, 0x2b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x66, 0x64, 0x79, 0x6d, 0x79, 0x6c, 0x6a, 0x61, 0x2f, 0x74, 0x6d, 0x6f, 0x73, 0x2f, 0x61,
	0x70, 0x69, 0x73, 0x2f, 0x72, 0x62, 0x61, 0x63, 0x2f, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61,
	0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_apis_rbac_v1alpha1_rbac_proto_rawDescOnce sync.Once
	file_apis_rbac_v1alpha1_rbac_proto_rawDescData = file_apis_rbac_v1alpha1_rbac_proto_rawDesc
)

func file_apis_rbac_v1alpha1_rbac_proto_rawDescGZIP() []byte {
	file_apis_rbac_v1alpha1_rbac_proto_rawDescOnce.Do(func() {
		file_apis_rbac_v1alpha1_rbac_proto_rawDescData = protoimpl.X.CompressGZIP(file_apis_rbac_v1alpha1_rbac_proto_rawDescData)
	})
	return file_apis_rbac_v1alpha1_rbac_proto_rawDescData
}

var file_apis_rbac_v1alpha1_rbac_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_apis_rbac_v1alpha1_rbac_proto_goTypes = []interface{}{
	(*Role)(nil),        // 0: tmos.rbac.v1alpha1.Role
	(*RoleBinding)(nil), // 1: tmos.rbac.v1alpha1.RoleBinding
}
var file_apis_rbac_v1alpha1_rbac_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_apis_rbac_v1alpha1_rbac_proto_init() }
func file_apis_rbac_v1alpha1_rbac_proto_init() {
	if File_apis_rbac_v1alpha1_rbac_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_apis_rbac_v1alpha1_rbac_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Role); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apis_rbac_v1alpha1_rbac_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoleBinding); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_apis_rbac_v1alpha1_rbac_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_apis_rbac_v1alpha1_rbac_proto_goTypes,
		DependencyIndexes: file_apis_rbac_v1alpha1_rbac_proto_depIdxs,
		MessageInfos:      file_apis_rbac_v1alpha1_rbac_proto_msgTypes,
	}.Build()
	File_apis_rbac_v1alpha1_rbac_proto = out.File
	file_apis_rbac_v1alpha1_rbac_proto_rawDesc = nil
	file_apis_rbac_v1alpha1_rbac_proto_goTypes = nil
	file_apis_rbac_v1alpha1_rbac_proto_depIdxs = nil
}
