// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.13.0
// source: module/rbac/v1alpha1/rbac.proto

package v1alpha1

import (
	reflect "reflect"
	sync "sync"

	v1alpha1 "github.com/fdymylja/tmos/module/runtime/v1alpha1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Role defines a role, which defines what resources
// can be accessed and which operations can be performed
// on those resources
type Role struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string          `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // external_account
	Resources []string        `protobuf:"bytes,2,rep,name=resources,proto3" json:"resources,omitempty"`
	Verbs     []v1alpha1.Verb `protobuf:"varint,3,rep,packed,name=verbs,proto3,enum=tmos.runtime.v1alpha1.Verb" json:"verbs,omitempty"`
}

func (x *Role) Reset() {
	*x = Role{}
	if protoimpl.UnsafeEnabled {
		mi := &file_module_rbac_v1alpha1_rbac_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Role) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Role) ProtoMessage() {}

func (x *Role) ProtoReflect() protoreflect.Message {
	mi := &file_module_rbac_v1alpha1_rbac_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Role.ProtoReflect.Descriptor instead.
func (*Role) Descriptor() ([]byte, []int) {
	return file_module_rbac_v1alpha1_rbac_proto_rawDescGZIP(), []int{0}
}

func (x *Role) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Role) GetResources() []string {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *Role) GetVerbs() []v1alpha1.Verb {
	if x != nil {
		return x.Verbs
	}
	return nil
}

// RoleBinding binds a subject to a role
type RoleBinding struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Subject string `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`                // uniquely identifies the account
	RoleRef string `protobuf:"bytes,2,opt,name=role_ref,json=roleRef,proto3" json:"role_ref,omitempty"` // points to Role
}

func (x *RoleBinding) Reset() {
	*x = RoleBinding{}
	if protoimpl.UnsafeEnabled {
		mi := &file_module_rbac_v1alpha1_rbac_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoleBinding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleBinding) ProtoMessage() {}

func (x *RoleBinding) ProtoReflect() protoreflect.Message {
	mi := &file_module_rbac_v1alpha1_rbac_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleBinding.ProtoReflect.Descriptor instead.
func (*RoleBinding) Descriptor() ([]byte, []int) {
	return file_module_rbac_v1alpha1_rbac_proto_rawDescGZIP(), []int{1}
}

func (x *RoleBinding) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *RoleBinding) GetRoleRef() string {
	if x != nil {
		return x.RoleRef
	}
	return ""
}

// MsgCreateRole creates a new role
type MsgCreateRole struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NewRole *Role `protobuf:"bytes,1,opt,name=new_role,json=newRole,proto3" json:"new_role,omitempty"`
}

func (x *MsgCreateRole) Reset() {
	*x = MsgCreateRole{}
	if protoimpl.UnsafeEnabled {
		mi := &file_module_rbac_v1alpha1_rbac_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgCreateRole) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgCreateRole) ProtoMessage() {}

func (x *MsgCreateRole) ProtoReflect() protoreflect.Message {
	mi := &file_module_rbac_v1alpha1_rbac_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgCreateRole.ProtoReflect.Descriptor instead.
func (*MsgCreateRole) Descriptor() ([]byte, []int) {
	return file_module_rbac_v1alpha1_rbac_proto_rawDescGZIP(), []int{2}
}

func (x *MsgCreateRole) GetNewRole() *Role {
	if x != nil {
		return x.NewRole
	}
	return nil
}

// MsgBindRole binds subject to role_id
type MsgBindRole struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleId  string `protobuf:"bytes,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	Subject string `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
}

func (x *MsgBindRole) Reset() {
	*x = MsgBindRole{}
	if protoimpl.UnsafeEnabled {
		mi := &file_module_rbac_v1alpha1_rbac_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgBindRole) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgBindRole) ProtoMessage() {}

func (x *MsgBindRole) ProtoReflect() protoreflect.Message {
	mi := &file_module_rbac_v1alpha1_rbac_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgBindRole.ProtoReflect.Descriptor instead.
func (*MsgBindRole) Descriptor() ([]byte, []int) {
	return file_module_rbac_v1alpha1_rbac_proto_rawDescGZIP(), []int{3}
}

func (x *MsgBindRole) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

func (x *MsgBindRole) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

var File_module_rbac_v1alpha1_rbac_proto protoreflect.FileDescriptor

var file_module_rbac_v1alpha1_rbac_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x2f, 0x72, 0x62, 0x61, 0x63, 0x2f, 0x76, 0x31,
	0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2f, 0x72, 0x62, 0x61, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x12, 0x74, 0x6d, 0x6f, 0x73, 0x2e, 0x72, 0x62, 0x61, 0x63, 0x2e, 0x76, 0x31, 0x61,
	0x6c, 0x70, 0x68, 0x61, 0x31, 0x1a, 0x25, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x2f, 0x72, 0x75,
	0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2f, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2f, 0x72,
	0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x67, 0x0a, 0x04,
	0x52, 0x6f, 0x6c, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x73, 0x12, 0x31, 0x0a, 0x05, 0x76, 0x65, 0x72, 0x62, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28,
	0x0e, 0x32, 0x1b, 0x2e, 0x74, 0x6d, 0x6f, 0x73, 0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65,
	0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x56, 0x65, 0x72, 0x62, 0x52, 0x05,
	0x76, 0x65, 0x72, 0x62, 0x73, 0x22, 0x42, 0x0a, 0x0b, 0x52, 0x6f, 0x6c, 0x65, 0x42, 0x69, 0x6e,
	0x64, 0x69, 0x6e, 0x67, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x19,
	0x0a, 0x08, 0x72, 0x6f, 0x6c, 0x65, 0x5f, 0x72, 0x65, 0x66, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x72, 0x6f, 0x6c, 0x65, 0x52, 0x65, 0x66, 0x22, 0x44, 0x0a, 0x0d, 0x4d, 0x73, 0x67,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x6c, 0x65, 0x12, 0x33, 0x0a, 0x08, 0x6e, 0x65,
	0x77, 0x5f, 0x72, 0x6f, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x74,
	0x6d, 0x6f, 0x73, 0x2e, 0x72, 0x62, 0x61, 0x63, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61,
	0x31, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x07, 0x6e, 0x65, 0x77, 0x52, 0x6f, 0x6c, 0x65, 0x22,
	0x40, 0x0a, 0x0b, 0x4d, 0x73, 0x67, 0x42, 0x69, 0x6e, 0x64, 0x52, 0x6f, 0x6c, 0x65, 0x12, 0x17,
	0x0a, 0x07, 0x72, 0x6f, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x72, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x62, 0x6a, 0x65,
	0x63, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63,
	0x74, 0x42, 0x2f, 0x5a, 0x2d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x66, 0x64, 0x79, 0x6d, 0x79, 0x6c, 0x6a, 0x61, 0x2f, 0x74, 0x6d, 0x6f, 0x73, 0x2f, 0x6d, 0x6f,
	0x64, 0x75, 0x6c, 0x65, 0x2f, 0x72, 0x62, 0x61, 0x63, 0x2f, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68,
	0x61, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_module_rbac_v1alpha1_rbac_proto_rawDescOnce sync.Once
	file_module_rbac_v1alpha1_rbac_proto_rawDescData = file_module_rbac_v1alpha1_rbac_proto_rawDesc
)

func file_module_rbac_v1alpha1_rbac_proto_rawDescGZIP() []byte {
	file_module_rbac_v1alpha1_rbac_proto_rawDescOnce.Do(func() {
		file_module_rbac_v1alpha1_rbac_proto_rawDescData = protoimpl.X.CompressGZIP(file_module_rbac_v1alpha1_rbac_proto_rawDescData)
	})
	return file_module_rbac_v1alpha1_rbac_proto_rawDescData
}

var file_module_rbac_v1alpha1_rbac_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_module_rbac_v1alpha1_rbac_proto_goTypes = []interface{}{
	(*Role)(nil),          // 0: tmos.rbac.v1alpha1.Role
	(*RoleBinding)(nil),   // 1: tmos.rbac.v1alpha1.RoleBinding
	(*MsgCreateRole)(nil), // 2: tmos.rbac.v1alpha1.MsgCreateRole
	(*MsgBindRole)(nil),   // 3: tmos.rbac.v1alpha1.MsgBindRole
	(v1alpha1.Verb)(0),    // 4: tmos.runtime.v1alpha1.Verb
}
var file_module_rbac_v1alpha1_rbac_proto_depIdxs = []int32{
	4, // 0: tmos.rbac.v1alpha1.Role.verbs:type_name -> tmos.runtime.v1alpha1.Verb
	0, // 1: tmos.rbac.v1alpha1.MsgCreateRole.new_role:type_name -> tmos.rbac.v1alpha1.Role
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_module_rbac_v1alpha1_rbac_proto_init() }
func file_module_rbac_v1alpha1_rbac_proto_init() {
	if File_module_rbac_v1alpha1_rbac_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_module_rbac_v1alpha1_rbac_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Role); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_module_rbac_v1alpha1_rbac_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoleBinding); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_module_rbac_v1alpha1_rbac_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgCreateRole); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_module_rbac_v1alpha1_rbac_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgBindRole); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_module_rbac_v1alpha1_rbac_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_module_rbac_v1alpha1_rbac_proto_goTypes,
		DependencyIndexes: file_module_rbac_v1alpha1_rbac_proto_depIdxs,
		MessageInfos:      file_module_rbac_v1alpha1_rbac_proto_msgTypes,
	}.Build()
	File_module_rbac_v1alpha1_rbac_proto = out.File
	file_module_rbac_v1alpha1_rbac_proto_rawDesc = nil
	file_module_rbac_v1alpha1_rbac_proto_goTypes = nil
	file_module_rbac_v1alpha1_rbac_proto_depIdxs = nil
}
