// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.13.0
// source: apis/core/runtime/v1alpha1/runtime.proto

package v1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RawTx defines the transaction that can be forwarded to the tendermint Check/DeliverTx endpoints
type RawTx struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// body is the actual transaction body
	// now... why is this an google.protobuf.Any instead of being a strongly defined type?
	// backwards compatibility and clear deprecation policies. We could have a core.tx.v1beta1.Tx
	// that we'd like to support but at the same time create a new core.tx.v2alpha1.Tx which we intend
	// to test and maybe deprecate the v1beta version in favor of this one, and not deal with them concurrently
	// as in the sdk!
	Body *anypb.Any `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
}

func (x *RawTx) Reset() {
	*x = RawTx{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apis_core_runtime_v1alpha1_runtime_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RawTx) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawTx) ProtoMessage() {}

func (x *RawTx) ProtoReflect() protoreflect.Message {
	mi := &file_apis_core_runtime_v1alpha1_runtime_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawTx.ProtoReflect.Descriptor instead.
func (*RawTx) Descriptor() ([]byte, []int) {
	return file_apis_core_runtime_v1alpha1_runtime_proto_rawDescGZIP(), []int{0}
}

func (x *RawTx) GetBody() *anypb.Any {
	if x != nil {
		return x.Body
	}
	return nil
}

// Query defines the query model that can be forwarded to make queries to the application
type Query struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// id is the unique identifier for the object
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// type defines the object type
	Type string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *Query) Reset() {
	*x = Query{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apis_core_runtime_v1alpha1_runtime_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Query) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Query) ProtoMessage() {}

func (x *Query) ProtoReflect() protoreflect.Message {
	mi := &file_apis_core_runtime_v1alpha1_runtime_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Query.ProtoReflect.Descriptor instead.
func (*Query) Descriptor() ([]byte, []int) {
	return file_apis_core_runtime_v1alpha1_runtime_proto_rawDescGZIP(), []int{1}
}

func (x *Query) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Query) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

var File_apis_core_runtime_v1alpha1_runtime_proto protoreflect.FileDescriptor

var file_apis_core_runtime_v1alpha1_runtime_proto_rawDesc = []byte{
	0x0a, 0x28, 0x61, 0x70, 0x69, 0x73, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x72, 0x75, 0x6e, 0x74,
	0x69, 0x6d, 0x65, 0x2f, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2f, 0x72, 0x75, 0x6e,
	0x74, 0x69, 0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x15, 0x63, 0x6f, 0x72, 0x65,
	0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61,
	0x31, 0x1a, 0x19, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x61, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x31, 0x0a, 0x05,
	0x52, 0x61, 0x77, 0x54, 0x78, 0x12, 0x28, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x22,
	0x2b, 0x0a, 0x05, 0x51, 0x75, 0x65, 0x72, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x42, 0x35, 0x5a, 0x33,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x66, 0x64, 0x79, 0x6d, 0x79,
	0x6c, 0x6a, 0x61, 0x2f, 0x74, 0x6d, 0x6f, 0x73, 0x2f, 0x61, 0x70, 0x69, 0x73, 0x2f, 0x63, 0x6f,
	0x72, 0x65, 0x2f, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2f, 0x76, 0x31, 0x61, 0x6c, 0x70,
	0x68, 0x61, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_apis_core_runtime_v1alpha1_runtime_proto_rawDescOnce sync.Once
	file_apis_core_runtime_v1alpha1_runtime_proto_rawDescData = file_apis_core_runtime_v1alpha1_runtime_proto_rawDesc
)

func file_apis_core_runtime_v1alpha1_runtime_proto_rawDescGZIP() []byte {
	file_apis_core_runtime_v1alpha1_runtime_proto_rawDescOnce.Do(func() {
		file_apis_core_runtime_v1alpha1_runtime_proto_rawDescData = protoimpl.X.CompressGZIP(file_apis_core_runtime_v1alpha1_runtime_proto_rawDescData)
	})
	return file_apis_core_runtime_v1alpha1_runtime_proto_rawDescData
}

var file_apis_core_runtime_v1alpha1_runtime_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_apis_core_runtime_v1alpha1_runtime_proto_goTypes = []interface{}{
	(*RawTx)(nil),     // 0: core.runtime.v1alpha1.RawTx
	(*Query)(nil),     // 1: core.runtime.v1alpha1.Query
	(*anypb.Any)(nil), // 2: google.protobuf.Any
}
var file_apis_core_runtime_v1alpha1_runtime_proto_depIdxs = []int32{
	2, // 0: core.runtime.v1alpha1.RawTx.body:type_name -> google.protobuf.Any
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_apis_core_runtime_v1alpha1_runtime_proto_init() }
func file_apis_core_runtime_v1alpha1_runtime_proto_init() {
	if File_apis_core_runtime_v1alpha1_runtime_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_apis_core_runtime_v1alpha1_runtime_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RawTx); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apis_core_runtime_v1alpha1_runtime_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Query); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_apis_core_runtime_v1alpha1_runtime_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_apis_core_runtime_v1alpha1_runtime_proto_goTypes,
		DependencyIndexes: file_apis_core_runtime_v1alpha1_runtime_proto_depIdxs,
		MessageInfos:      file_apis_core_runtime_v1alpha1_runtime_proto_msgTypes,
	}.Build()
	File_apis_core_runtime_v1alpha1_runtime_proto = out.File
	file_apis_core_runtime_v1alpha1_runtime_proto_rawDesc = nil
	file_apis_core_runtime_v1alpha1_runtime_proto_goTypes = nil
	file_apis_core_runtime_v1alpha1_runtime_proto_depIdxs = nil
}
