// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.13.0
// source: core/modulegen/modulegen.proto

package modulegen

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// StateTransitionDescriptor describes a state transition
type StateTransitionDescriptor struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StateTransitionDescriptor) Reset() {
	*x = StateTransitionDescriptor{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_modulegen_modulegen_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StateTransitionDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateTransitionDescriptor) ProtoMessage() {}

func (x *StateTransitionDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_core_modulegen_modulegen_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateTransitionDescriptor.ProtoReflect.Descriptor instead.
func (*StateTransitionDescriptor) Descriptor() ([]byte, []int) {
	return file_core_modulegen_modulegen_proto_rawDescGZIP(), []int{0}
}

type StateObjectDescriptor struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Singleton     bool     `protobuf:"varint,1,opt,name=singleton,proto3" json:"singleton,omitempty"`
	PrimaryKey    string   `protobuf:"bytes,2,opt,name=primary_key,json=primaryKey,proto3" json:"primary_key,omitempty"`
	SecondaryKeys []string `protobuf:"bytes,3,rep,name=secondary_keys,json=secondaryKeys,proto3" json:"secondary_keys,omitempty"`
}

func (x *StateObjectDescriptor) Reset() {
	*x = StateObjectDescriptor{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_modulegen_modulegen_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StateObjectDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateObjectDescriptor) ProtoMessage() {}

func (x *StateObjectDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_core_modulegen_modulegen_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateObjectDescriptor.ProtoReflect.Descriptor instead.
func (*StateObjectDescriptor) Descriptor() ([]byte, []int) {
	return file_core_modulegen_modulegen_proto_rawDescGZIP(), []int{1}
}

func (x *StateObjectDescriptor) GetSingleton() bool {
	if x != nil {
		return x.Singleton
	}
	return false
}

func (x *StateObjectDescriptor) GetPrimaryKey() string {
	if x != nil {
		return x.PrimaryKey
	}
	return ""
}

func (x *StateObjectDescriptor) GetSecondaryKeys() []string {
	if x != nil {
		return x.SecondaryKeys
	}
	return nil
}

var file_core_modulegen_modulegen_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*StateTransitionDescriptor)(nil),
		Field:         1110001,
		Name:          "tmos.core.modulegen.state_transition",
		Tag:           "bytes,1110001,opt,name=state_transition",
		Filename:      "core/modulegen/modulegen.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*StateObjectDescriptor)(nil),
		Field:         1110002,
		Name:          "tmos.core.modulegen.state_object",
		Tag:           "bytes,1110002,opt,name=state_object",
		Filename:      "core/modulegen/modulegen.proto",
	},
}

// Extension fields to descriptorpb.MessageOptions.
var (
	// optional tmos.core.modulegen.StateTransitionDescriptor state_transition = 1110001;
	E_StateTransition = &file_core_modulegen_modulegen_proto_extTypes[0]
	// optional tmos.core.modulegen.StateObjectDescriptor state_object = 1110002;
	E_StateObject = &file_core_modulegen_modulegen_proto_extTypes[1]
)

var File_core_modulegen_modulegen_proto protoreflect.FileDescriptor

var file_core_modulegen_modulegen_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x67, 0x65, 0x6e,
	0x2f, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x67, 0x65, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x13, 0x74, 0x6d, 0x6f, 0x73, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x6d, 0x6f, 0x64, 0x75,
	0x6c, 0x65, 0x67, 0x65, 0x6e, 0x1a, 0x20, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f,
	0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x1b, 0x0a, 0x19, 0x53, 0x74, 0x61, 0x74, 0x65,
	0x54, 0x72, 0x61, 0x6e, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x6f, 0x72, 0x22, 0x7d, 0x0a, 0x15, 0x53, 0x74, 0x61, 0x74, 0x65, 0x4f, 0x62, 0x6a,
	0x65, 0x63, 0x74, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x12, 0x1c, 0x0a,
	0x09, 0x73, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x74, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x09, 0x73, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x74, 0x6f, 0x6e, 0x12, 0x1f, 0x0a, 0x0b, 0x70,
	0x72, 0x69, 0x6d, 0x61, 0x72, 0x79, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x70, 0x72, 0x69, 0x6d, 0x61, 0x72, 0x79, 0x4b, 0x65, 0x79, 0x12, 0x25, 0x0a, 0x0e,
	0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x61, 0x72, 0x79, 0x5f, 0x6b, 0x65, 0x79, 0x73, 0x18, 0x03,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x0d, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x61, 0x72, 0x79, 0x4b,
	0x65, 0x79, 0x73, 0x3a, 0x7c, 0x0a, 0x10, 0x73, 0x74, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x72, 0x61,
	0x6e, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1f, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0xf1, 0xdf, 0x43, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x2e, 0x2e, 0x74, 0x6d, 0x6f, 0x73, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x6d, 0x6f, 0x64,
	0x75, 0x6c, 0x65, 0x67, 0x65, 0x6e, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x54, 0x72, 0x61, 0x6e,
	0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72,
	0x52, 0x0f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x3a, 0x70, 0x0a, 0x0c, 0x73, 0x74, 0x61, 0x74, 0x65, 0x5f, 0x6f, 0x62, 0x6a, 0x65, 0x63,
	0x74, 0x12, 0x1f, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x18, 0xf2, 0xdf, 0x43, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x74, 0x6d, 0x6f,
	0x73, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x67, 0x65, 0x6e,
	0x2e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x44, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x52, 0x0b, 0x73, 0x74, 0x61, 0x74, 0x65, 0x4f, 0x62, 0x6a,
	0x65, 0x63, 0x74, 0x42, 0x29, 0x5a, 0x27, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x66, 0x64, 0x79, 0x6d, 0x79, 0x6c, 0x6a, 0x61, 0x2f, 0x74, 0x6d, 0x6f, 0x73, 0x2f,
	0x63, 0x6f, 0x72, 0x65, 0x2f, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x67, 0x65, 0x6e, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_core_modulegen_modulegen_proto_rawDescOnce sync.Once
	file_core_modulegen_modulegen_proto_rawDescData = file_core_modulegen_modulegen_proto_rawDesc
)

func file_core_modulegen_modulegen_proto_rawDescGZIP() []byte {
	file_core_modulegen_modulegen_proto_rawDescOnce.Do(func() {
		file_core_modulegen_modulegen_proto_rawDescData = protoimpl.X.CompressGZIP(file_core_modulegen_modulegen_proto_rawDescData)
	})
	return file_core_modulegen_modulegen_proto_rawDescData
}

var file_core_modulegen_modulegen_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_core_modulegen_modulegen_proto_goTypes = []interface{}{
	(*StateTransitionDescriptor)(nil),   // 0: tmos.core.modulegen.StateTransitionDescriptor
	(*StateObjectDescriptor)(nil),       // 1: tmos.core.modulegen.StateObjectDescriptor
	(*descriptorpb.MessageOptions)(nil), // 2: google.protobuf.MessageOptions
}
var file_core_modulegen_modulegen_proto_depIdxs = []int32{
	2, // 0: tmos.core.modulegen.state_transition:extendee -> google.protobuf.MessageOptions
	2, // 1: tmos.core.modulegen.state_object:extendee -> google.protobuf.MessageOptions
	0, // 2: tmos.core.modulegen.state_transition:type_name -> tmos.core.modulegen.StateTransitionDescriptor
	1, // 3: tmos.core.modulegen.state_object:type_name -> tmos.core.modulegen.StateObjectDescriptor
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	2, // [2:4] is the sub-list for extension type_name
	0, // [0:2] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_core_modulegen_modulegen_proto_init() }
func file_core_modulegen_modulegen_proto_init() {
	if File_core_modulegen_modulegen_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_core_modulegen_modulegen_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StateTransitionDescriptor); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_modulegen_modulegen_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StateObjectDescriptor); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_core_modulegen_modulegen_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 2,
			NumServices:   0,
		},
		GoTypes:           file_core_modulegen_modulegen_proto_goTypes,
		DependencyIndexes: file_core_modulegen_modulegen_proto_depIdxs,
		MessageInfos:      file_core_modulegen_modulegen_proto_msgTypes,
		ExtensionInfos:    file_core_modulegen_modulegen_proto_extTypes,
	}.Build()
	File_core_modulegen_modulegen_proto = out.File
	file_core_modulegen_modulegen_proto_rawDesc = nil
	file_core_modulegen_modulegen_proto_goTypes = nil
	file_core_modulegen_modulegen_proto_depIdxs = nil
}
