// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.13.0
// source: core/runtime/v1alpha1/module.proto

package v1alpha1

import (
	meta "github.com/fdymylja/tmos/core/meta"
	_ "github.com/fdymylja/tmos/core/modulegen"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ModuleDescriptors struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Modules []*ModuleDescriptor `protobuf:"bytes,1,rep,name=modules,proto3" json:"modules,omitempty"`
}

func (x *ModuleDescriptors) Reset() {
	*x = ModuleDescriptors{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_runtime_v1alpha1_module_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModuleDescriptors) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModuleDescriptors) ProtoMessage() {}

func (x *ModuleDescriptors) ProtoReflect() protoreflect.Message {
	mi := &file_core_runtime_v1alpha1_module_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModuleDescriptors.ProtoReflect.Descriptor instead.
func (*ModuleDescriptors) Descriptor() ([]byte, []int) {
	return file_core_runtime_v1alpha1_module_proto_rawDescGZIP(), []int{0}
}

func (x *ModuleDescriptors) GetModules() []*ModuleDescriptor {
	if x != nil {
		return x.Modules
	}
	return nil
}

type CreateModuleDescriptors struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Modules []*ModuleDescriptor `protobuf:"bytes,1,rep,name=modules,proto3" json:"modules,omitempty"`
}

func (x *CreateModuleDescriptors) Reset() {
	*x = CreateModuleDescriptors{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_runtime_v1alpha1_module_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateModuleDescriptors) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateModuleDescriptors) ProtoMessage() {}

func (x *CreateModuleDescriptors) ProtoReflect() protoreflect.Message {
	mi := &file_core_runtime_v1alpha1_module_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateModuleDescriptors.ProtoReflect.Descriptor instead.
func (*CreateModuleDescriptors) Descriptor() ([]byte, []int) {
	return file_core_runtime_v1alpha1_module_proto_rawDescGZIP(), []int{1}
}

func (x *CreateModuleDescriptors) GetModules() []*ModuleDescriptor {
	if x != nil {
		return x.Modules
	}
	return nil
}

// StateObject describes a state object
type StateObject struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ApiDefinition    *meta.APIDefinition `protobuf:"bytes,1,opt,name=api_definition,json=apiDefinition,proto3" json:"api_definition,omitempty"`
	ProtobufFullname string              `protobuf:"bytes,2,opt,name=protobuf_fullname,json=protobufFullname,proto3" json:"protobuf_fullname,omitempty"`
	SchemaDefinition *SchemaDefinition   `protobuf:"bytes,3,opt,name=schema_definition,json=schemaDefinition,proto3" json:"schema_definition,omitempty"`
}

func (x *StateObject) Reset() {
	*x = StateObject{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_runtime_v1alpha1_module_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StateObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateObject) ProtoMessage() {}

func (x *StateObject) ProtoReflect() protoreflect.Message {
	mi := &file_core_runtime_v1alpha1_module_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateObject.ProtoReflect.Descriptor instead.
func (*StateObject) Descriptor() ([]byte, []int) {
	return file_core_runtime_v1alpha1_module_proto_rawDescGZIP(), []int{2}
}

func (x *StateObject) GetApiDefinition() *meta.APIDefinition {
	if x != nil {
		return x.ApiDefinition
	}
	return nil
}

func (x *StateObject) GetProtobufFullname() string {
	if x != nil {
		return x.ProtobufFullname
	}
	return ""
}

func (x *StateObject) GetSchemaDefinition() *SchemaDefinition {
	if x != nil {
		return x.SchemaDefinition
	}
	return nil
}

// StateTransition describes a state transition
type StateTransition struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ApiDefinition    *meta.APIDefinition `protobuf:"bytes,1,opt,name=api_definition,json=apiDefinition,proto3" json:"api_definition,omitempty"`
	ProtobufFullname string              `protobuf:"bytes,2,opt,name=protobuf_fullname,json=protobufFullname,proto3" json:"protobuf_fullname,omitempty"`
}

func (x *StateTransition) Reset() {
	*x = StateTransition{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_runtime_v1alpha1_module_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StateTransition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateTransition) ProtoMessage() {}

func (x *StateTransition) ProtoReflect() protoreflect.Message {
	mi := &file_core_runtime_v1alpha1_module_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateTransition.ProtoReflect.Descriptor instead.
func (*StateTransition) Descriptor() ([]byte, []int) {
	return file_core_runtime_v1alpha1_module_proto_rawDescGZIP(), []int{3}
}

func (x *StateTransition) GetApiDefinition() *meta.APIDefinition {
	if x != nil {
		return x.ApiDefinition
	}
	return nil
}

func (x *StateTransition) GetProtobufFullname() string {
	if x != nil {
		return x.ProtobufFullname
	}
	return ""
}

// SchemaDefinition describes the orm.Schema of a state object
type SchemaDefinition struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// singleton marks if there can exist only one instance of this object
	// it's invalid to use primary key alongside a Singleton
	Singleton bool `protobuf:"varint,1,opt,name=singleton,proto3" json:"singleton,omitempty"`
	// primary_key indicates the field to use as a primary key
	// it must be the json name of the protobuf object
	// NOTE: primary_key must not be set if Singleton is true
	PrimaryKey string `protobuf:"bytes,2,opt,name=primary_key,json=primaryKey,proto3" json:"primary_key,omitempty"`
	// secondary_key indicates the protobuf json names of fields
	// of the object to use as secondary keys, the ones that can be
	// passed to the List() endpoints
	// NOTE: secondary_keys must not be set if Singleton is true
	SecondaryKeys []string `protobuf:"bytes,3,rep,name=secondary_keys,json=secondaryKeys,proto3" json:"secondary_keys,omitempty"`
}

func (x *SchemaDefinition) Reset() {
	*x = SchemaDefinition{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_runtime_v1alpha1_module_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SchemaDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchemaDefinition) ProtoMessage() {}

func (x *SchemaDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_core_runtime_v1alpha1_module_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchemaDefinition.ProtoReflect.Descriptor instead.
func (*SchemaDefinition) Descriptor() ([]byte, []int) {
	return file_core_runtime_v1alpha1_module_proto_rawDescGZIP(), []int{4}
}

func (x *SchemaDefinition) GetSingleton() bool {
	if x != nil {
		return x.Singleton
	}
	return false
}

func (x *SchemaDefinition) GetPrimaryKey() string {
	if x != nil {
		return x.PrimaryKey
	}
	return ""
}

func (x *SchemaDefinition) GetSecondaryKeys() []string {
	if x != nil {
		return x.SecondaryKeys
	}
	return nil
}

// ModuleDescriptor describes a module
type ModuleDescriptor struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name             string             `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	StateObjects     []*StateObject     `protobuf:"bytes,2,rep,name=state_objects,json=stateObjects,proto3" json:"state_objects,omitempty"`
	StateTransitions []*StateTransition `protobuf:"bytes,3,rep,name=state_transitions,json=stateTransitions,proto3" json:"state_transitions,omitempty"`
}

func (x *ModuleDescriptor) Reset() {
	*x = ModuleDescriptor{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_runtime_v1alpha1_module_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModuleDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModuleDescriptor) ProtoMessage() {}

func (x *ModuleDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_core_runtime_v1alpha1_module_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModuleDescriptor.ProtoReflect.Descriptor instead.
func (*ModuleDescriptor) Descriptor() ([]byte, []int) {
	return file_core_runtime_v1alpha1_module_proto_rawDescGZIP(), []int{5}
}

func (x *ModuleDescriptor) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ModuleDescriptor) GetStateObjects() []*StateObject {
	if x != nil {
		return x.StateObjects
	}
	return nil
}

func (x *ModuleDescriptor) GetStateTransitions() []*StateTransition {
	if x != nil {
		return x.StateTransitions
	}
	return nil
}

var File_core_runtime_v1alpha1_module_proto protoreflect.FileDescriptor

var file_core_runtime_v1alpha1_module_proto_rawDesc = []byte{
	0x0a, 0x22, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2f, 0x76,
	0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2f, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x15, 0x74, 0x6d, 0x6f, 0x73, 0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69,
	0x6d, 0x65, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x1a, 0x1e, 0x63, 0x6f, 0x72,
	0x65, 0x2f, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x67, 0x65, 0x6e, 0x2f, 0x6d, 0x6f, 0x64, 0x75,
	0x6c, 0x65, 0x67, 0x65, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x14, 0x63, 0x6f, 0x72,
	0x65, 0x2f, 0x6d, 0x65, 0x74, 0x61, 0x2f, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x5f, 0x0a, 0x11, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x44, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x6f, 0x72, 0x73, 0x12, 0x41, 0x0a, 0x07, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x74, 0x6d, 0x6f, 0x73, 0x2e, 0x72,
	0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e,
	0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72,
	0x52, 0x07, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x73, 0x3a, 0x07, 0x92, 0xff, 0x9d, 0x04, 0x02,
	0x08, 0x01, 0x22, 0x63, 0x0a, 0x17, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x6f, 0x64, 0x75,
	0x6c, 0x65, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x73, 0x12, 0x41, 0x0a,
	0x07, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x27,
	0x2e, 0x74, 0x6d, 0x6f, 0x73, 0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x76, 0x31,
	0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x44, 0x65, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x52, 0x07, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x73,
	0x3a, 0x05, 0x8a, 0xff, 0x9d, 0x04, 0x00, 0x22, 0xda, 0x01, 0x0a, 0x0b, 0x53, 0x74, 0x61, 0x74,
	0x65, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x48, 0x0a, 0x0e, 0x61, 0x70, 0x69, 0x5f, 0x64,
	0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x21, 0x2e, 0x74, 0x6d, 0x6f, 0x73, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x76, 0x31, 0x61, 0x6c,
	0x70, 0x68, 0x61, 0x31, 0x2e, 0x41, 0x50, 0x49, 0x44, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x0d, 0x61, 0x70, 0x69, 0x44, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x2b, 0x0a, 0x11, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x5f, 0x66, 0x75,
	0x6c, 0x6c, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x46, 0x75, 0x6c, 0x6c, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x54,
	0x0a, 0x11, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x5f, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x74, 0x6d, 0x6f, 0x73,
	0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61,
	0x31, 0x2e, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x44, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x10, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x44, 0x65, 0x66, 0x69, 0x6e, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x22, 0x88, 0x01, 0x0a, 0x0f, 0x53, 0x74, 0x61, 0x74, 0x65, 0x54, 0x72,
	0x61, 0x6e, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x48, 0x0a, 0x0e, 0x61, 0x70, 0x69, 0x5f,
	0x64, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x21, 0x2e, 0x74, 0x6d, 0x6f, 0x73, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x76, 0x31, 0x61,
	0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x41, 0x50, 0x49, 0x44, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x0d, 0x61, 0x70, 0x69, 0x44, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x2b, 0x0a, 0x11, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x5f, 0x66,
	0x75, 0x6c, 0x6c, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x46, 0x75, 0x6c, 0x6c, 0x6e, 0x61, 0x6d, 0x65, 0x22,
	0x78, 0x0a, 0x10, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x44, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x74, 0x6f, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x73, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x74, 0x6f,
	0x6e, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x72, 0x69, 0x6d, 0x61, 0x72, 0x79, 0x5f, 0x6b, 0x65, 0x79,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x72, 0x69, 0x6d, 0x61, 0x72, 0x79, 0x4b,
	0x65, 0x79, 0x12, 0x25, 0x0a, 0x0e, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x61, 0x72, 0x79, 0x5f,
	0x6b, 0x65, 0x79, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0d, 0x73, 0x65, 0x63, 0x6f,
	0x6e, 0x64, 0x61, 0x72, 0x79, 0x4b, 0x65, 0x79, 0x73, 0x22, 0xc4, 0x01, 0x0a, 0x10, 0x4d, 0x6f,
	0x64, 0x75, 0x6c, 0x65, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x47, 0x0a, 0x0d, 0x73, 0x74, 0x61, 0x74, 0x65, 0x5f, 0x6f, 0x62, 0x6a, 0x65,
	0x63, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x74, 0x6d, 0x6f, 0x73,
	0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61,
	0x31, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x0c, 0x73,
	0x74, 0x61, 0x74, 0x65, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x12, 0x53, 0x0a, 0x11, 0x73,
	0x74, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x74, 0x6d, 0x6f, 0x73, 0x2e, 0x72, 0x75,
	0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x53,
	0x74, 0x61, 0x74, 0x65, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x10,
	0x73, 0x74, 0x61, 0x74, 0x65, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x42, 0x30, 0x5a, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x66,
	0x64, 0x79, 0x6d, 0x79, 0x6c, 0x6a, 0x61, 0x2f, 0x74, 0x6d, 0x6f, 0x73, 0x2f, 0x63, 0x6f, 0x72,
	0x65, 0x2f, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2f, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68,
	0x61, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_core_runtime_v1alpha1_module_proto_rawDescOnce sync.Once
	file_core_runtime_v1alpha1_module_proto_rawDescData = file_core_runtime_v1alpha1_module_proto_rawDesc
)

func file_core_runtime_v1alpha1_module_proto_rawDescGZIP() []byte {
	file_core_runtime_v1alpha1_module_proto_rawDescOnce.Do(func() {
		file_core_runtime_v1alpha1_module_proto_rawDescData = protoimpl.X.CompressGZIP(file_core_runtime_v1alpha1_module_proto_rawDescData)
	})
	return file_core_runtime_v1alpha1_module_proto_rawDescData
}

var file_core_runtime_v1alpha1_module_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_core_runtime_v1alpha1_module_proto_goTypes = []interface{}{
	(*ModuleDescriptors)(nil),       // 0: tmos.runtime.v1alpha1.ModuleDescriptors
	(*CreateModuleDescriptors)(nil), // 1: tmos.runtime.v1alpha1.CreateModuleDescriptors
	(*StateObject)(nil),             // 2: tmos.runtime.v1alpha1.StateObject
	(*StateTransition)(nil),         // 3: tmos.runtime.v1alpha1.StateTransition
	(*SchemaDefinition)(nil),        // 4: tmos.runtime.v1alpha1.SchemaDefinition
	(*ModuleDescriptor)(nil),        // 5: tmos.runtime.v1alpha1.ModuleDescriptor
	(*meta.APIDefinition)(nil),      // 6: tmos.meta.v1alpha1.APIDefinition
}
var file_core_runtime_v1alpha1_module_proto_depIdxs = []int32{
	5, // 0: tmos.runtime.v1alpha1.ModuleDescriptors.modules:type_name -> tmos.runtime.v1alpha1.ModuleDescriptor
	5, // 1: tmos.runtime.v1alpha1.CreateModuleDescriptors.modules:type_name -> tmos.runtime.v1alpha1.ModuleDescriptor
	6, // 2: tmos.runtime.v1alpha1.StateObject.api_definition:type_name -> tmos.meta.v1alpha1.APIDefinition
	4, // 3: tmos.runtime.v1alpha1.StateObject.schema_definition:type_name -> tmos.runtime.v1alpha1.SchemaDefinition
	6, // 4: tmos.runtime.v1alpha1.StateTransition.api_definition:type_name -> tmos.meta.v1alpha1.APIDefinition
	2, // 5: tmos.runtime.v1alpha1.ModuleDescriptor.state_objects:type_name -> tmos.runtime.v1alpha1.StateObject
	3, // 6: tmos.runtime.v1alpha1.ModuleDescriptor.state_transitions:type_name -> tmos.runtime.v1alpha1.StateTransition
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_core_runtime_v1alpha1_module_proto_init() }
func file_core_runtime_v1alpha1_module_proto_init() {
	if File_core_runtime_v1alpha1_module_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_core_runtime_v1alpha1_module_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModuleDescriptors); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_runtime_v1alpha1_module_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateModuleDescriptors); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_runtime_v1alpha1_module_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StateObject); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_runtime_v1alpha1_module_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StateTransition); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_runtime_v1alpha1_module_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SchemaDefinition); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_runtime_v1alpha1_module_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModuleDescriptor); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_core_runtime_v1alpha1_module_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_core_runtime_v1alpha1_module_proto_goTypes,
		DependencyIndexes: file_core_runtime_v1alpha1_module_proto_depIdxs,
		MessageInfos:      file_core_runtime_v1alpha1_module_proto_msgTypes,
	}.Build()
	File_core_runtime_v1alpha1_module_proto = out.File
	file_core_runtime_v1alpha1_module_proto_rawDesc = nil
	file_core_runtime_v1alpha1_module_proto_goTypes = nil
	file_core_runtime_v1alpha1_module_proto_depIdxs = nil
}
