// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.13.0
// source: core/runtime/v1alpha1/module.proto

package v1alpha1

import (
	module "github.com/fdymylja/tmos/core/module"
	_ "github.com/fdymylja/tmos/core/modulegen"
	_ "github.com/fdymylja/tmos/core/rbac/xt"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ModuleDescriptors struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Modules []*module.Descriptor `protobuf:"bytes,1,rep,name=modules,proto3" json:"modules,omitempty"`
}

func (x *ModuleDescriptors) Reset() {
	*x = ModuleDescriptors{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_runtime_v1alpha1_module_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModuleDescriptors) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModuleDescriptors) ProtoMessage() {}

func (x *ModuleDescriptors) ProtoReflect() protoreflect.Message {
	mi := &file_core_runtime_v1alpha1_module_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModuleDescriptors.ProtoReflect.Descriptor instead.
func (*ModuleDescriptors) Descriptor() ([]byte, []int) {
	return file_core_runtime_v1alpha1_module_proto_rawDescGZIP(), []int{0}
}

func (x *ModuleDescriptors) GetModules() []*module.Descriptor {
	if x != nil {
		return x.Modules
	}
	return nil
}

type CreateModuleDescriptors struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Modules []*module.Descriptor `protobuf:"bytes,1,rep,name=modules,proto3" json:"modules,omitempty"`
}

func (x *CreateModuleDescriptors) Reset() {
	*x = CreateModuleDescriptors{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_runtime_v1alpha1_module_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateModuleDescriptors) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateModuleDescriptors) ProtoMessage() {}

func (x *CreateModuleDescriptors) ProtoReflect() protoreflect.Message {
	mi := &file_core_runtime_v1alpha1_module_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateModuleDescriptors.ProtoReflect.Descriptor instead.
func (*CreateModuleDescriptors) Descriptor() ([]byte, []int) {
	return file_core_runtime_v1alpha1_module_proto_rawDescGZIP(), []int{1}
}

func (x *CreateModuleDescriptors) GetModules() []*module.Descriptor {
	if x != nil {
		return x.Modules
	}
	return nil
}

var File_core_runtime_v1alpha1_module_proto protoreflect.FileDescriptor

var file_core_runtime_v1alpha1_module_proto_rawDesc = []byte{
	0x0a, 0x22, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2f, 0x76,
	0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2f, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x15, 0x74, 0x6d, 0x6f, 0x73, 0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69,
	0x6d, 0x65, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x1a, 0x1e, 0x63, 0x6f, 0x72,
	0x65, 0x2f, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x67, 0x65, 0x6e, 0x2f, 0x6d, 0x6f, 0x64, 0x75,
	0x6c, 0x65, 0x67, 0x65, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x18, 0x63, 0x6f, 0x72,
	0x65, 0x2f, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x2f, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x21, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x72, 0x62, 0x61, 0x63,
	0x2f, 0x78, 0x74, 0x2f, 0x72, 0x62, 0x61, 0x63, 0x5f, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69,
	0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x57, 0x0a, 0x11, 0x4d, 0x6f, 0x64, 0x75,
	0x6c, 0x65, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x73, 0x12, 0x39, 0x0a,
	0x07, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f,
	0x2e, 0x74, 0x6d, 0x6f, 0x73, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x6d, 0x6f, 0x64, 0x75, 0x6c,
	0x65, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x52,
	0x07, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x73, 0x3a, 0x07, 0x92, 0xff, 0x9d, 0x04, 0x02, 0x08,
	0x01, 0x22, 0x60, 0x0a, 0x17, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x6f, 0x64, 0x75, 0x6c,
	0x65, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x73, 0x12, 0x39, 0x0a, 0x07,
	0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e,
	0x74, 0x6d, 0x6f, 0x73, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65,
	0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x52, 0x07,
	0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x73, 0x3a, 0x0a, 0x8a, 0xff, 0x9d, 0x04, 0x00, 0x82, 0xb0,
	0xe3, 0x2d, 0x00, 0x42, 0x30, 0x5a, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x66, 0x64, 0x79, 0x6d, 0x79, 0x6c, 0x6a, 0x61, 0x2f, 0x74, 0x6d, 0x6f, 0x73, 0x2f,
	0x63, 0x6f, 0x72, 0x65, 0x2f, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2f, 0x76, 0x31, 0x61,
	0x6c, 0x70, 0x68, 0x61, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_core_runtime_v1alpha1_module_proto_rawDescOnce sync.Once
	file_core_runtime_v1alpha1_module_proto_rawDescData = file_core_runtime_v1alpha1_module_proto_rawDesc
)

func file_core_runtime_v1alpha1_module_proto_rawDescGZIP() []byte {
	file_core_runtime_v1alpha1_module_proto_rawDescOnce.Do(func() {
		file_core_runtime_v1alpha1_module_proto_rawDescData = protoimpl.X.CompressGZIP(file_core_runtime_v1alpha1_module_proto_rawDescData)
	})
	return file_core_runtime_v1alpha1_module_proto_rawDescData
}

var file_core_runtime_v1alpha1_module_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_core_runtime_v1alpha1_module_proto_goTypes = []interface{}{
	(*ModuleDescriptors)(nil),       // 0: tmos.runtime.v1alpha1.ModuleDescriptors
	(*CreateModuleDescriptors)(nil), // 1: tmos.runtime.v1alpha1.CreateModuleDescriptors
	(*module.Descriptor)(nil),       // 2: tmos.core.module.v1.Descriptor
}
var file_core_runtime_v1alpha1_module_proto_depIdxs = []int32{
	2, // 0: tmos.runtime.v1alpha1.ModuleDescriptors.modules:type_name -> tmos.core.module.v1.Descriptor
	2, // 1: tmos.runtime.v1alpha1.CreateModuleDescriptors.modules:type_name -> tmos.core.module.v1.Descriptor
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_core_runtime_v1alpha1_module_proto_init() }
func file_core_runtime_v1alpha1_module_proto_init() {
	if File_core_runtime_v1alpha1_module_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_core_runtime_v1alpha1_module_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModuleDescriptors); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_runtime_v1alpha1_module_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateModuleDescriptors); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_core_runtime_v1alpha1_module_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_core_runtime_v1alpha1_module_proto_goTypes,
		DependencyIndexes: file_core_runtime_v1alpha1_module_proto_depIdxs,
		MessageInfos:      file_core_runtime_v1alpha1_module_proto_msgTypes,
	}.Build()
	File_core_runtime_v1alpha1_module_proto = out.File
	file_core_runtime_v1alpha1_module_proto_rawDesc = nil
	file_core_runtime_v1alpha1_module_proto_goTypes = nil
	file_core_runtime_v1alpha1_module_proto_depIdxs = nil
}
