// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.13.0
// source: core/runtime/v1alpha1/module.proto

package v1alpha1

import (
	_ "github.com/fdymylja/tmos/core/modulegen"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// StateObjectsList provides the list of state objects
// represented as protobuf.Fullname(meta.StateObject)
type StateObjectsList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StateObjects []string `protobuf:"bytes,1,rep,name=state_objects,json=stateObjects,proto3" json:"state_objects,omitempty"`
}

func (x *StateObjectsList) Reset() {
	*x = StateObjectsList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_runtime_v1alpha1_module_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StateObjectsList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateObjectsList) ProtoMessage() {}

func (x *StateObjectsList) ProtoReflect() protoreflect.Message {
	mi := &file_core_runtime_v1alpha1_module_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateObjectsList.ProtoReflect.Descriptor instead.
func (*StateObjectsList) Descriptor() ([]byte, []int) {
	return file_core_runtime_v1alpha1_module_proto_rawDescGZIP(), []int{0}
}

func (x *StateObjectsList) GetStateObjects() []string {
	if x != nil {
		return x.StateObjects
	}
	return nil
}

// StateTransitionsList provides the list of state transitions
// that can be delivered to the runtime represented as protobuf.Fullname(meta.StateTransition)
type StateTransitionsList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StateTransitions []string `protobuf:"bytes,1,rep,name=state_transitions,json=stateTransitions,proto3" json:"state_transitions,omitempty"`
}

func (x *StateTransitionsList) Reset() {
	*x = StateTransitionsList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_runtime_v1alpha1_module_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StateTransitionsList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateTransitionsList) ProtoMessage() {}

func (x *StateTransitionsList) ProtoReflect() protoreflect.Message {
	mi := &file_core_runtime_v1alpha1_module_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateTransitionsList.ProtoReflect.Descriptor instead.
func (*StateTransitionsList) Descriptor() ([]byte, []int) {
	return file_core_runtime_v1alpha1_module_proto_rawDescGZIP(), []int{1}
}

func (x *StateTransitionsList) GetStateTransitions() []string {
	if x != nil {
		return x.StateTransitions
	}
	return nil
}

type CreateStateObjectsList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StateObjects []string `protobuf:"bytes,1,rep,name=state_objects,json=stateObjects,proto3" json:"state_objects,omitempty"`
}

func (x *CreateStateObjectsList) Reset() {
	*x = CreateStateObjectsList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_runtime_v1alpha1_module_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateStateObjectsList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStateObjectsList) ProtoMessage() {}

func (x *CreateStateObjectsList) ProtoReflect() protoreflect.Message {
	mi := &file_core_runtime_v1alpha1_module_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStateObjectsList.ProtoReflect.Descriptor instead.
func (*CreateStateObjectsList) Descriptor() ([]byte, []int) {
	return file_core_runtime_v1alpha1_module_proto_rawDescGZIP(), []int{2}
}

func (x *CreateStateObjectsList) GetStateObjects() []string {
	if x != nil {
		return x.StateObjects
	}
	return nil
}

type CreateStateTransitionsList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StateTransitions []string `protobuf:"bytes,1,rep,name=state_transitions,json=stateTransitions,proto3" json:"state_transitions,omitempty"`
}

func (x *CreateStateTransitionsList) Reset() {
	*x = CreateStateTransitionsList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_runtime_v1alpha1_module_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateStateTransitionsList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStateTransitionsList) ProtoMessage() {}

func (x *CreateStateTransitionsList) ProtoReflect() protoreflect.Message {
	mi := &file_core_runtime_v1alpha1_module_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStateTransitionsList.ProtoReflect.Descriptor instead.
func (*CreateStateTransitionsList) Descriptor() ([]byte, []int) {
	return file_core_runtime_v1alpha1_module_proto_rawDescGZIP(), []int{3}
}

func (x *CreateStateTransitionsList) GetStateTransitions() []string {
	if x != nil {
		return x.StateTransitions
	}
	return nil
}

var File_core_runtime_v1alpha1_module_proto protoreflect.FileDescriptor

var file_core_runtime_v1alpha1_module_proto_rawDesc = []byte{
	0x0a, 0x22, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2f, 0x76,
	0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2f, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x15, 0x74, 0x6d, 0x6f, 0x73, 0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69,
	0x6d, 0x65, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x1a, 0x1e, 0x63, 0x6f, 0x72,
	0x65, 0x2f, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x67, 0x65, 0x6e, 0x2f, 0x6d, 0x6f, 0x64, 0x75,
	0x6c, 0x65, 0x67, 0x65, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x40, 0x0a, 0x10, 0x53,
	0x74, 0x61, 0x74, 0x65, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x12,
	0x23, 0x0a, 0x0d, 0x73, 0x74, 0x61, 0x74, 0x65, 0x5f, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0c, 0x73, 0x74, 0x61, 0x74, 0x65, 0x4f, 0x62, 0x6a,
	0x65, 0x63, 0x74, 0x73, 0x3a, 0x07, 0x92, 0xff, 0x9d, 0x04, 0x02, 0x08, 0x01, 0x22, 0x4c, 0x0a,
	0x14, 0x53, 0x74, 0x61, 0x74, 0x65, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x2b, 0x0a, 0x11, 0x73, 0x74, 0x61, 0x74, 0x65, 0x5f, 0x74,
	0x72, 0x61, 0x6e, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x10, 0x73, 0x74, 0x61, 0x74, 0x65, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x3a, 0x07, 0x92, 0xff, 0x9d, 0x04, 0x02, 0x08, 0x01, 0x22, 0x44, 0x0a, 0x16, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74,
	0x73, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x73, 0x74, 0x61, 0x74, 0x65, 0x5f, 0x6f,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0c, 0x73, 0x74,
	0x61, 0x74, 0x65, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x3a, 0x05, 0x8a, 0xff, 0x9d, 0x04,
	0x00, 0x22, 0x50, 0x0a, 0x1a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65,
	0x54, 0x72, 0x61, 0x6e, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x12,
	0x2b, 0x0a, 0x11, 0x73, 0x74, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x10, 0x73, 0x74, 0x61, 0x74,
	0x65, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x3a, 0x05, 0x8a, 0xff,
	0x9d, 0x04, 0x00, 0x42, 0x30, 0x5a, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x66, 0x64, 0x79, 0x6d, 0x79, 0x6c, 0x6a, 0x61, 0x2f, 0x74, 0x6d, 0x6f, 0x73, 0x2f,
	0x63, 0x6f, 0x72, 0x65, 0x2f, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2f, 0x76, 0x31, 0x61,
	0x6c, 0x70, 0x68, 0x61, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_core_runtime_v1alpha1_module_proto_rawDescOnce sync.Once
	file_core_runtime_v1alpha1_module_proto_rawDescData = file_core_runtime_v1alpha1_module_proto_rawDesc
)

func file_core_runtime_v1alpha1_module_proto_rawDescGZIP() []byte {
	file_core_runtime_v1alpha1_module_proto_rawDescOnce.Do(func() {
		file_core_runtime_v1alpha1_module_proto_rawDescData = protoimpl.X.CompressGZIP(file_core_runtime_v1alpha1_module_proto_rawDescData)
	})
	return file_core_runtime_v1alpha1_module_proto_rawDescData
}

var file_core_runtime_v1alpha1_module_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_core_runtime_v1alpha1_module_proto_goTypes = []interface{}{
	(*StateObjectsList)(nil),           // 0: tmos.runtime.v1alpha1.StateObjectsList
	(*StateTransitionsList)(nil),       // 1: tmos.runtime.v1alpha1.StateTransitionsList
	(*CreateStateObjectsList)(nil),     // 2: tmos.runtime.v1alpha1.CreateStateObjectsList
	(*CreateStateTransitionsList)(nil), // 3: tmos.runtime.v1alpha1.CreateStateTransitionsList
}
var file_core_runtime_v1alpha1_module_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_core_runtime_v1alpha1_module_proto_init() }
func file_core_runtime_v1alpha1_module_proto_init() {
	if File_core_runtime_v1alpha1_module_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_core_runtime_v1alpha1_module_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StateObjectsList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_runtime_v1alpha1_module_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StateTransitionsList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_runtime_v1alpha1_module_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateStateObjectsList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_runtime_v1alpha1_module_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateStateTransitionsList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_core_runtime_v1alpha1_module_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_core_runtime_v1alpha1_module_proto_goTypes,
		DependencyIndexes: file_core_runtime_v1alpha1_module_proto_depIdxs,
		MessageInfos:      file_core_runtime_v1alpha1_module_proto_msgTypes,
	}.Build()
	File_core_runtime_v1alpha1_module_proto = out.File
	file_core_runtime_v1alpha1_module_proto_rawDesc = nil
	file_core_runtime_v1alpha1_module_proto_goTypes = nil
	file_core_runtime_v1alpha1_module_proto_depIdxs = nil
}
