// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.13.0
// source: core/runtime/v1alpha1/query.proto

package v1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Resources defines the list of API resources
// known to the runtime
type Resources struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ApiGroupResources []*APIGroupResources `protobuf:"bytes,1,rep,name=api_group_resources,json=apiGroupResources,proto3" json:"api_group_resources,omitempty"`
}

func (x *Resources) Reset() {
	*x = Resources{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_runtime_v1alpha1_query_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Resources) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resources) ProtoMessage() {}

func (x *Resources) ProtoReflect() protoreflect.Message {
	mi := &file_core_runtime_v1alpha1_query_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resources.ProtoReflect.Descriptor instead.
func (*Resources) Descriptor() ([]byte, []int) {
	return file_core_runtime_v1alpha1_query_proto_rawDescGZIP(), []int{0}
}

func (x *Resources) GetApiGroupResources() []*APIGroupResources {
	if x != nil {
		return x.ApiGroupResources
	}
	return nil
}

type APIGroupResources struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ApiGroup         string   `protobuf:"bytes,1,opt,name=api_group,json=apiGroup,proto3" json:"api_group,omitempty"`
	StateObjects     []string `protobuf:"bytes,2,rep,name=state_objects,json=stateObjects,proto3" json:"state_objects,omitempty"`
	StateTransitions []string `protobuf:"bytes,3,rep,name=state_transitions,json=stateTransitions,proto3" json:"state_transitions,omitempty"`
}

func (x *APIGroupResources) Reset() {
	*x = APIGroupResources{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_runtime_v1alpha1_query_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *APIGroupResources) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIGroupResources) ProtoMessage() {}

func (x *APIGroupResources) ProtoReflect() protoreflect.Message {
	mi := &file_core_runtime_v1alpha1_query_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIGroupResources.ProtoReflect.Descriptor instead.
func (*APIGroupResources) Descriptor() ([]byte, []int) {
	return file_core_runtime_v1alpha1_query_proto_rawDescGZIP(), []int{1}
}

func (x *APIGroupResources) GetApiGroup() string {
	if x != nil {
		return x.ApiGroup
	}
	return ""
}

func (x *APIGroupResources) GetStateObjects() []string {
	if x != nil {
		return x.StateObjects
	}
	return nil
}

func (x *APIGroupResources) GetStateTransitions() []string {
	if x != nil {
		return x.StateTransitions
	}
	return nil
}

var File_core_runtime_v1alpha1_query_proto protoreflect.FileDescriptor

var file_core_runtime_v1alpha1_query_proto_rawDesc = []byte{
	0x0a, 0x21, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2f, 0x76,
	0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2f, 0x71, 0x75, 0x65, 0x72, 0x79, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x15, 0x74, 0x6d, 0x6f, 0x73, 0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d,
	0x65, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x22, 0x65, 0x0a, 0x09, 0x52, 0x65,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x12, 0x58, 0x0a, 0x13, 0x61, 0x70, 0x69, 0x5f, 0x67,
	0x72, 0x6f, 0x75, 0x70, 0x5f, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x74, 0x6d, 0x6f, 0x73, 0x2e, 0x72, 0x75, 0x6e, 0x74,
	0x69, 0x6d, 0x65, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x41, 0x50, 0x49,
	0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x52, 0x11,
	0x61, 0x70, 0x69, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x73, 0x22, 0x82, 0x01, 0x0a, 0x11, 0x41, 0x50, 0x49, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x61, 0x70, 0x69, 0x5f, 0x67,
	0x72, 0x6f, 0x75, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x61, 0x70, 0x69, 0x47,
	0x72, 0x6f, 0x75, 0x70, 0x12, 0x23, 0x0a, 0x0d, 0x73, 0x74, 0x61, 0x74, 0x65, 0x5f, 0x6f, 0x62,
	0x6a, 0x65, 0x63, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0c, 0x73, 0x74, 0x61,
	0x74, 0x65, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x12, 0x2b, 0x0a, 0x11, 0x73, 0x74, 0x61,
	0x74, 0x65, 0x5f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x03,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x10, 0x73, 0x74, 0x61, 0x74, 0x65, 0x54, 0x72, 0x61, 0x6e, 0x73,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x42, 0x30, 0x5a, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x66, 0x64, 0x79, 0x6d, 0x79, 0x6c, 0x6a, 0x61, 0x2f, 0x74, 0x6d,
	0x6f, 0x73, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2f,
	0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_core_runtime_v1alpha1_query_proto_rawDescOnce sync.Once
	file_core_runtime_v1alpha1_query_proto_rawDescData = file_core_runtime_v1alpha1_query_proto_rawDesc
)

func file_core_runtime_v1alpha1_query_proto_rawDescGZIP() []byte {
	file_core_runtime_v1alpha1_query_proto_rawDescOnce.Do(func() {
		file_core_runtime_v1alpha1_query_proto_rawDescData = protoimpl.X.CompressGZIP(file_core_runtime_v1alpha1_query_proto_rawDescData)
	})
	return file_core_runtime_v1alpha1_query_proto_rawDescData
}

var file_core_runtime_v1alpha1_query_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_core_runtime_v1alpha1_query_proto_goTypes = []interface{}{
	(*Resources)(nil),         // 0: tmos.runtime.v1alpha1.Resources
	(*APIGroupResources)(nil), // 1: tmos.runtime.v1alpha1.APIGroupResources
}
var file_core_runtime_v1alpha1_query_proto_depIdxs = []int32{
	1, // 0: tmos.runtime.v1alpha1.Resources.api_group_resources:type_name -> tmos.runtime.v1alpha1.APIGroupResources
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_core_runtime_v1alpha1_query_proto_init() }
func file_core_runtime_v1alpha1_query_proto_init() {
	if File_core_runtime_v1alpha1_query_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_core_runtime_v1alpha1_query_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Resources); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_runtime_v1alpha1_query_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*APIGroupResources); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_core_runtime_v1alpha1_query_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_core_runtime_v1alpha1_query_proto_goTypes,
		DependencyIndexes: file_core_runtime_v1alpha1_query_proto_depIdxs,
		MessageInfos:      file_core_runtime_v1alpha1_query_proto_msgTypes,
	}.Build()
	File_core_runtime_v1alpha1_query_proto = out.File
	file_core_runtime_v1alpha1_query_proto_rawDesc = nil
	file_core_runtime_v1alpha1_query_proto_goTypes = nil
	file_core_runtime_v1alpha1_query_proto_depIdxs = nil
}
