// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.13.0
// source: module/x/bank/v1alpha1/bank.proto

package v1alpha1

import (
	v1alpha1 "github.com/fdymylja/tmos/module/core/coin/v1alpha1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MsgSendCoins struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FromAddress string           `protobuf:"bytes,1,opt,name=from_address,json=fromAddress,proto3" json:"from_address,omitempty"`
	ToAddress   string           `protobuf:"bytes,2,opt,name=to_address,json=toAddress,proto3" json:"to_address,omitempty"`
	Amount      []*v1alpha1.Coin `protobuf:"bytes,3,rep,name=amount,proto3" json:"amount,omitempty"`
}

func (x *MsgSendCoins) Reset() {
	*x = MsgSendCoins{}
	if protoimpl.UnsafeEnabled {
		mi := &file_module_x_bank_v1alpha1_bank_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgSendCoins) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgSendCoins) ProtoMessage() {}

func (x *MsgSendCoins) ProtoReflect() protoreflect.Message {
	mi := &file_module_x_bank_v1alpha1_bank_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgSendCoins.ProtoReflect.Descriptor instead.
func (*MsgSendCoins) Descriptor() ([]byte, []int) {
	return file_module_x_bank_v1alpha1_bank_proto_rawDescGZIP(), []int{0}
}

func (x *MsgSendCoins) GetFromAddress() string {
	if x != nil {
		return x.FromAddress
	}
	return ""
}

func (x *MsgSendCoins) GetToAddress() string {
	if x != nil {
		return x.ToAddress
	}
	return ""
}

func (x *MsgSendCoins) GetAmount() []*v1alpha1.Coin {
	if x != nil {
		return x.Amount
	}
	return nil
}

type MsgSetBalance struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address string           `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Amount  []*v1alpha1.Coin `protobuf:"bytes,2,rep,name=amount,proto3" json:"amount,omitempty"`
}

func (x *MsgSetBalance) Reset() {
	*x = MsgSetBalance{}
	if protoimpl.UnsafeEnabled {
		mi := &file_module_x_bank_v1alpha1_bank_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgSetBalance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgSetBalance) ProtoMessage() {}

func (x *MsgSetBalance) ProtoReflect() protoreflect.Message {
	mi := &file_module_x_bank_v1alpha1_bank_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgSetBalance.ProtoReflect.Descriptor instead.
func (*MsgSetBalance) Descriptor() ([]byte, []int) {
	return file_module_x_bank_v1alpha1_bank_proto_rawDescGZIP(), []int{1}
}

func (x *MsgSetBalance) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *MsgSetBalance) GetAmount() []*v1alpha1.Coin {
	if x != nil {
		return x.Amount
	}
	return nil
}

type Balance struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// address identifies the user who owns balance TODO: i'd rename this user...
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	// balance represents the balance of the user
	Balance []*v1alpha1.Coin `protobuf:"bytes,2,rep,name=balance,proto3" json:"balance,omitempty"`
}

func (x *Balance) Reset() {
	*x = Balance{}
	if protoimpl.UnsafeEnabled {
		mi := &file_module_x_bank_v1alpha1_bank_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Balance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Balance) ProtoMessage() {}

func (x *Balance) ProtoReflect() protoreflect.Message {
	mi := &file_module_x_bank_v1alpha1_bank_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Balance.ProtoReflect.Descriptor instead.
func (*Balance) Descriptor() ([]byte, []int) {
	return file_module_x_bank_v1alpha1_bank_proto_rawDescGZIP(), []int{2}
}

func (x *Balance) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Balance) GetBalance() []*v1alpha1.Coin {
	if x != nil {
		return x.Balance
	}
	return nil
}

var File_module_x_bank_v1alpha1_bank_proto protoreflect.FileDescriptor

var file_module_x_bank_v1alpha1_bank_proto_rawDesc = []byte{
	0x0a, 0x21, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x2f, 0x78, 0x2f, 0x62, 0x61, 0x6e, 0x6b, 0x2f,
	0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2f, 0x62, 0x61, 0x6e, 0x6b, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x14, 0x74, 0x6d, 0x6f, 0x73, 0x2e, 0x78, 0x2e, 0x62, 0x61, 0x6e, 0x6b,
	0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x1a, 0x24, 0x6d, 0x6f, 0x64, 0x75, 0x6c,
	0x65, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x63, 0x6f, 0x69, 0x6e, 0x2f, 0x76, 0x31, 0x61, 0x6c,
	0x70, 0x68, 0x61, 0x31, 0x2f, 0x63, 0x6f, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x87, 0x01, 0x0a, 0x0c, 0x4d, 0x73, 0x67, 0x53, 0x65, 0x6e, 0x64, 0x43, 0x6f, 0x69, 0x6e, 0x73,
	0x12, 0x21, 0x0a, 0x0c, 0x66, 0x72, 0x6f, 0x6d, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x66, 0x72, 0x6f, 0x6d, 0x41, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x6f, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x6f, 0x41, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x12, 0x35, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x74, 0x6d, 0x6f, 0x73, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x63,
	0x6f, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x43, 0x6f, 0x69,
	0x6e, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x60, 0x0a, 0x0d, 0x4d, 0x73, 0x67,
	0x53, 0x65, 0x74, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x12, 0x35, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x74, 0x6d, 0x6f, 0x73, 0x2e, 0x63, 0x6f, 0x72, 0x65,
	0x2e, 0x63, 0x6f, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x43,
	0x6f, 0x69, 0x6e, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x5c, 0x0a, 0x07, 0x42,
	0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x12, 0x37, 0x0a, 0x07, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x1d, 0x2e, 0x74, 0x6d, 0x6f, 0x73, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x63, 0x6f,
	0x69, 0x6e, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x43, 0x6f, 0x69, 0x6e,
	0x52, 0x07, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x42, 0x31, 0x5a, 0x2f, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x66, 0x64, 0x79, 0x6d, 0x79, 0x6c, 0x6a, 0x61,
	0x2f, 0x74, 0x6d, 0x6f, 0x73, 0x2f, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x2f, 0x78, 0x2f, 0x62,
	0x61, 0x6e, 0x6b, 0x2f, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_module_x_bank_v1alpha1_bank_proto_rawDescOnce sync.Once
	file_module_x_bank_v1alpha1_bank_proto_rawDescData = file_module_x_bank_v1alpha1_bank_proto_rawDesc
)

func file_module_x_bank_v1alpha1_bank_proto_rawDescGZIP() []byte {
	file_module_x_bank_v1alpha1_bank_proto_rawDescOnce.Do(func() {
		file_module_x_bank_v1alpha1_bank_proto_rawDescData = protoimpl.X.CompressGZIP(file_module_x_bank_v1alpha1_bank_proto_rawDescData)
	})
	return file_module_x_bank_v1alpha1_bank_proto_rawDescData
}

var file_module_x_bank_v1alpha1_bank_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_module_x_bank_v1alpha1_bank_proto_goTypes = []interface{}{
	(*MsgSendCoins)(nil),  // 0: tmos.x.bank.v1alpha1.MsgSendCoins
	(*MsgSetBalance)(nil), // 1: tmos.x.bank.v1alpha1.MsgSetBalance
	(*Balance)(nil),       // 2: tmos.x.bank.v1alpha1.Balance
	(*v1alpha1.Coin)(nil), // 3: tmos.core.coin.v1alpha1.Coin
}
var file_module_x_bank_v1alpha1_bank_proto_depIdxs = []int32{
	3, // 0: tmos.x.bank.v1alpha1.MsgSendCoins.amount:type_name -> tmos.core.coin.v1alpha1.Coin
	3, // 1: tmos.x.bank.v1alpha1.MsgSetBalance.amount:type_name -> tmos.core.coin.v1alpha1.Coin
	3, // 2: tmos.x.bank.v1alpha1.Balance.balance:type_name -> tmos.core.coin.v1alpha1.Coin
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_module_x_bank_v1alpha1_bank_proto_init() }
func file_module_x_bank_v1alpha1_bank_proto_init() {
	if File_module_x_bank_v1alpha1_bank_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_module_x_bank_v1alpha1_bank_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgSendCoins); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_module_x_bank_v1alpha1_bank_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgSetBalance); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_module_x_bank_v1alpha1_bank_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Balance); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_module_x_bank_v1alpha1_bank_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_module_x_bank_v1alpha1_bank_proto_goTypes,
		DependencyIndexes: file_module_x_bank_v1alpha1_bank_proto_depIdxs,
		MessageInfos:      file_module_x_bank_v1alpha1_bank_proto_msgTypes,
	}.Build()
	File_module_x_bank_v1alpha1_bank_proto = out.File
	file_module_x_bank_v1alpha1_bank_proto_rawDesc = nil
	file_module_x_bank_v1alpha1_bank_proto_goTypes = nil
	file_module_x_bank_v1alpha1_bank_proto_depIdxs = nil
}
