// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.13.0
// source: module/abci/v1alpha1/abci.proto

package v1alpha1

import (
	abci "github.com/fdymylja/tmos/module/abci/tendermint/abci"
	v1alpha1 "github.com/fdymylja/tmos/module/meta/v1alpha1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BeginBlockState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ObjectMeta *v1alpha1.ObjectMeta    `protobuf:"bytes,1,opt,name=object_meta,json=objectMeta,proto3" json:"object_meta,omitempty"`
	BeginBlock *abci.RequestBeginBlock `protobuf:"bytes,2,opt,name=begin_block,json=beginBlock,proto3" json:"begin_block,omitempty"`
}

func (x *BeginBlockState) Reset() {
	*x = BeginBlockState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apis_abci_v1alpha1_abci_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BeginBlockState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeginBlockState) ProtoMessage() {}

func (x *BeginBlockState) ProtoReflect() protoreflect.Message {
	mi := &file_apis_abci_v1alpha1_abci_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeginBlockState.ProtoReflect.Descriptor instead.
func (*BeginBlockState) Descriptor() ([]byte, []int) {
	return file_apis_abci_v1alpha1_abci_proto_rawDescGZIP(), []int{0}
}

func (x *BeginBlockState) GetObjectMeta() *v1alpha1.ObjectMeta {
	if x != nil {
		return x.ObjectMeta
	}
	return nil
}

func (x *BeginBlockState) GetBeginBlock() *abci.RequestBeginBlock {
	if x != nil {
		return x.BeginBlock
	}
	return nil
}

type MsgSetBeginBlockState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TransitionMeta *v1alpha1.TransitionMeta `protobuf:"bytes,1,opt,name=transition_meta,json=transitionMeta,proto3" json:"transition_meta,omitempty"`
	BeginBlock     *abci.RequestBeginBlock  `protobuf:"bytes,2,opt,name=begin_block,json=beginBlock,proto3" json:"begin_block,omitempty"`
}

func (x *MsgSetBeginBlockState) Reset() {
	*x = MsgSetBeginBlockState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apis_abci_v1alpha1_abci_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgSetBeginBlockState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgSetBeginBlockState) ProtoMessage() {}

func (x *MsgSetBeginBlockState) ProtoReflect() protoreflect.Message {
	mi := &file_apis_abci_v1alpha1_abci_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgSetBeginBlockState.ProtoReflect.Descriptor instead.
func (*MsgSetBeginBlockState) Descriptor() ([]byte, []int) {
	return file_apis_abci_v1alpha1_abci_proto_rawDescGZIP(), []int{1}
}

func (x *MsgSetBeginBlockState) GetTransitionMeta() *v1alpha1.TransitionMeta {
	if x != nil {
		return x.TransitionMeta
	}
	return nil
}

func (x *MsgSetBeginBlockState) GetBeginBlock() *abci.RequestBeginBlock {
	if x != nil {
		return x.BeginBlock
	}
	return nil
}

var File_apis_abci_v1alpha1_abci_proto protoreflect.FileDescriptor

var file_apis_abci_v1alpha1_abci_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x61, 0x70, 0x69, 0x73, 0x2f, 0x61, 0x62, 0x63, 0x69, 0x2f, 0x76, 0x31, 0x61, 0x6c,
	0x70, 0x68, 0x61, 0x31, 0x2f, 0x61, 0x62, 0x63, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x12, 0x74, 0x6d, 0x6f, 0x73, 0x2e, 0x61, 0x62, 0x63, 0x69, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70,
	0x68, 0x61, 0x31, 0x1a, 0x1d, 0x61, 0x70, 0x69, 0x73, 0x2f, 0x6d, 0x65, 0x74, 0x61, 0x2f, 0x76,
	0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2f, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x25, 0x61, 0x70, 0x69, 0x73, 0x2f, 0x61, 0x62, 0x63, 0x69, 0x2f, 0x74, 0x65,
	0x6e, 0x64, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x74, 0x2f, 0x61, 0x62, 0x63, 0x69, 0x2f, 0x74, 0x79,
	0x70, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x97, 0x01, 0x0a, 0x0f, 0x42, 0x65,
	0x67, 0x69, 0x6e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x3f, 0x0a,
	0x0b, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x6d, 0x65, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x74, 0x6d, 0x6f, 0x73, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x76,
	0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x4d, 0x65,
	0x74, 0x61, 0x52, 0x0a, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x12, 0x43,
	0x0a, 0x0b, 0x62, 0x65, 0x67, 0x69, 0x6e, 0x5f, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x74, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x74,
	0x2e, 0x61, 0x62, 0x63, 0x69, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x42, 0x65, 0x67,
	0x69, 0x6e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x0a, 0x62, 0x65, 0x67, 0x69, 0x6e, 0x42, 0x6c,
	0x6f, 0x63, 0x6b, 0x22, 0xa9, 0x01, 0x0a, 0x15, 0x4d, 0x73, 0x67, 0x53, 0x65, 0x74, 0x42, 0x65,
	0x67, 0x69, 0x6e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x4b, 0x0a,
	0x0f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6d, 0x65, 0x74, 0x61,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x74, 0x6d, 0x6f, 0x73, 0x2e, 0x6d, 0x65,
	0x74, 0x61, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x54, 0x72, 0x61, 0x6e,
	0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x0e, 0x74, 0x72, 0x61, 0x6e,
	0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x74, 0x61, 0x12, 0x43, 0x0a, 0x0b, 0x62, 0x65,
	0x67, 0x69, 0x6e, 0x5f, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x22, 0x2e, 0x74, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x74, 0x2e, 0x61, 0x62, 0x63,
	0x69, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x42, 0x65, 0x67, 0x69, 0x6e, 0x42, 0x6c,
	0x6f, 0x63, 0x6b, 0x52, 0x0a, 0x62, 0x65, 0x67, 0x69, 0x6e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x42,
	0x2d, 0x5a, 0x2b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x66, 0x64,
	0x79, 0x6d, 0x79, 0x6c, 0x6a, 0x61, 0x2f, 0x74, 0x6d, 0x6f, 0x73, 0x2f, 0x61, 0x70, 0x69, 0x73,
	0x2f, 0x61, 0x62, 0x63, 0x69, 0x2f, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_apis_abci_v1alpha1_abci_proto_rawDescOnce sync.Once
	file_apis_abci_v1alpha1_abci_proto_rawDescData = file_apis_abci_v1alpha1_abci_proto_rawDesc
)

func file_apis_abci_v1alpha1_abci_proto_rawDescGZIP() []byte {
	file_apis_abci_v1alpha1_abci_proto_rawDescOnce.Do(func() {
		file_apis_abci_v1alpha1_abci_proto_rawDescData = protoimpl.X.CompressGZIP(file_apis_abci_v1alpha1_abci_proto_rawDescData)
	})
	return file_apis_abci_v1alpha1_abci_proto_rawDescData
}

var file_apis_abci_v1alpha1_abci_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_apis_abci_v1alpha1_abci_proto_goTypes = []interface{}{
	(*BeginBlockState)(nil),         // 0: tmos.abci.v1alpha1.BeginBlockState
	(*MsgSetBeginBlockState)(nil),   // 1: tmos.abci.v1alpha1.MsgSetBeginBlockState
	(*v1alpha1.ObjectMeta)(nil),     // 2: tmos.meta.v1alpha1.ObjectMeta
	(*abci.RequestBeginBlock)(nil),  // 3: tendermint.abci.RequestBeginBlock
	(*v1alpha1.TransitionMeta)(nil), // 4: tmos.meta.v1alpha1.TransitionMeta
}
var file_apis_abci_v1alpha1_abci_proto_depIdxs = []int32{
	2, // 0: tmos.abci.v1alpha1.BeginBlockState.object_meta:type_name -> tmos.meta.v1alpha1.ObjectMeta
	3, // 1: tmos.abci.v1alpha1.BeginBlockState.begin_block:type_name -> tendermint.abci.RequestBeginBlock
	4, // 2: tmos.abci.v1alpha1.MsgSetBeginBlockState.transition_meta:type_name -> tmos.meta.v1alpha1.TransitionMeta
	3, // 3: tmos.abci.v1alpha1.MsgSetBeginBlockState.begin_block:type_name -> tendermint.abci.RequestBeginBlock
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_apis_abci_v1alpha1_abci_proto_init() }
func file_apis_abci_v1alpha1_abci_proto_init() {
	if File_apis_abci_v1alpha1_abci_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_apis_abci_v1alpha1_abci_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BeginBlockState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apis_abci_v1alpha1_abci_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgSetBeginBlockState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_apis_abci_v1alpha1_abci_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_apis_abci_v1alpha1_abci_proto_goTypes,
		DependencyIndexes: file_apis_abci_v1alpha1_abci_proto_depIdxs,
		MessageInfos:      file_apis_abci_v1alpha1_abci_proto_msgTypes,
	}.Build()
	File_apis_abci_v1alpha1_abci_proto = out.File
	file_apis_abci_v1alpha1_abci_proto_rawDesc = nil
	file_apis_abci_v1alpha1_abci_proto_goTypes = nil
	file_apis_abci_v1alpha1_abci_proto_depIdxs = nil
}
