// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.13.0
// source: core/meta/meta.proto

package meta

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ResourceType marks the type of a resource
type ResourceType int32

const (
	// StateObject is a resource that is saved into storage
	ResourceType_StateObject ResourceType = 0
	// StateTransition is a resource that is not saved into storage
	// but is used to modify state.
	ResourceType_StateTransition ResourceType = 1
)

// Enum value maps for ResourceType.
var (
	ResourceType_name = map[int32]string{
		0: "StateObject",
		1: "StateTransition",
	}
	ResourceType_value = map[string]int32{
		"StateObject":     0,
		"StateTransition": 1,
	}
)

func (x ResourceType) Enum() *ResourceType {
	p := new(ResourceType)
	*p = x
	return p
}

func (x ResourceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResourceType) Descriptor() protoreflect.EnumDescriptor {
	return file_core_meta_meta_proto_enumTypes[0].Descriptor()
}

func (ResourceType) Type() protoreflect.EnumType {
	return &file_core_meta_meta_proto_enumTypes[0]
}

func (x ResourceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResourceType.Descriptor instead.
func (ResourceType) EnumDescriptor() ([]byte, []int) {
	return file_core_meta_meta_proto_rawDescGZIP(), []int{0}
}

// ResourceDefinition defines a resource
type ResourceDefinition struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// group defines the name of the group the resource belongs to (ex: x.bank.v1alpha1;)
	Group string `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	// kind defines the unique name of the resource in the group it belongs to (ex: balance)
	Kind string `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	// resource_type marks the resource type
	ResourceType ResourceType `protobuf:"varint,3,opt,name=resource_type,json=resourceType,proto3,enum=tmos.meta.v1alpha1.ResourceType" json:"resource_type,omitempty"`
}

func (x *ResourceDefinition) Reset() {
	*x = ResourceDefinition{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_meta_meta_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResourceDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceDefinition) ProtoMessage() {}

func (x *ResourceDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_core_meta_meta_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceDefinition.ProtoReflect.Descriptor instead.
func (*ResourceDefinition) Descriptor() ([]byte, []int) {
	return file_core_meta_meta_proto_rawDescGZIP(), []int{0}
}

func (x *ResourceDefinition) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *ResourceDefinition) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ResourceDefinition) GetResourceType() ResourceType {
	if x != nil {
		return x.ResourceType
	}
	return ResourceType_StateObject
}

var File_core_meta_meta_proto protoreflect.FileDescriptor

var file_core_meta_meta_proto_rawDesc = []byte{
	0x0a, 0x14, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x6d, 0x65, 0x74, 0x61, 0x2f, 0x6d, 0x65, 0x74, 0x61,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12, 0x74, 0x6d, 0x6f, 0x73, 0x2e, 0x6d, 0x65, 0x74,
	0x61, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x22, 0x85, 0x01, 0x0a, 0x12, 0x52,
	0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x44, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x14, 0x0a, 0x05, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x12, 0x45, 0x0a, 0x0d, 0x72,
	0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x20, 0x2e, 0x74, 0x6d, 0x6f, 0x73, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x76,
	0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x54, 0x79, 0x70, 0x65, 0x52, 0x0c, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x54, 0x79,
	0x70, 0x65, 0x2a, 0x34, 0x0a, 0x0c, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x0f, 0x0a, 0x0b, 0x53, 0x74, 0x61, 0x74, 0x65, 0x4f, 0x62, 0x6a, 0x65, 0x63,
	0x74, 0x10, 0x00, 0x12, 0x13, 0x0a, 0x0f, 0x53, 0x74, 0x61, 0x74, 0x65, 0x54, 0x72, 0x61, 0x6e,
	0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x10, 0x01, 0x42, 0x24, 0x5a, 0x22, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x66, 0x64, 0x79, 0x6d, 0x79, 0x6c, 0x6a, 0x61, 0x2f,
	0x74, 0x6d, 0x6f, 0x73, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x6d, 0x65, 0x74, 0x61, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_core_meta_meta_proto_rawDescOnce sync.Once
	file_core_meta_meta_proto_rawDescData = file_core_meta_meta_proto_rawDesc
)

func file_core_meta_meta_proto_rawDescGZIP() []byte {
	file_core_meta_meta_proto_rawDescOnce.Do(func() {
		file_core_meta_meta_proto_rawDescData = protoimpl.X.CompressGZIP(file_core_meta_meta_proto_rawDescData)
	})
	return file_core_meta_meta_proto_rawDescData
}

var file_core_meta_meta_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_core_meta_meta_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_core_meta_meta_proto_goTypes = []interface{}{
	(ResourceType)(0),          // 0: tmos.meta.v1alpha1.ResourceType
	(*ResourceDefinition)(nil), // 1: tmos.meta.v1alpha1.ResourceDefinition
}
var file_core_meta_meta_proto_depIdxs = []int32{
	0, // 0: tmos.meta.v1alpha1.ResourceDefinition.resource_type:type_name -> tmos.meta.v1alpha1.ResourceType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_core_meta_meta_proto_init() }
func file_core_meta_meta_proto_init() {
	if File_core_meta_meta_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_core_meta_meta_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResourceDefinition); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_core_meta_meta_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_core_meta_meta_proto_goTypes,
		DependencyIndexes: file_core_meta_meta_proto_depIdxs,
		EnumInfos:         file_core_meta_meta_proto_enumTypes,
		MessageInfos:      file_core_meta_meta_proto_msgTypes,
	}.Build()
	File_core_meta_meta_proto = out.File
	file_core_meta_meta_proto_rawDesc = nil
	file_core_meta_meta_proto_goTypes = nil
	file_core_meta_meta_proto_depIdxs = nil
}
